wget configs-web.agario.miniclippt.com/live/v7/1006/poland_hi.png -O poland.png
wget configs-web.agario.miniclippt.com/live/v7/1006/usa_hi.png -O usa.png
wget configs-web.agario.miniclippt.com/live/v7/1006/china_hi.png -O china.png
wget configs-web.agario.miniclippt.com/live/v7/1006/russia_hi.png -O russia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/canada_hi.png -O canada.png
wget configs-web.agario.miniclippt.com/live/v7/1006/australia_hi.png -O australia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/spain_hi.png -O spain.png
wget configs-web.agario.miniclippt.com/live/v7/1006/brazil_hi.png -O brazil.png
wget configs-web.agario.miniclippt.com/live/v7/1006/germany_hi.png -O germany.png
wget configs-web.agario.miniclippt.com/live/v7/1006/ukraine_hi.png -O ukraine.png
wget configs-web.agario.miniclippt.com/live/v7/1006/france_hi.png -O france.png
wget configs-web.agario.miniclippt.com/live/v7/1006/sweden_hi.png -O sweden.png
wget configs-web.agario.miniclippt.com/live/v7/1006/north_korea_hi.png -O north\ korea.png
wget configs-web.agario.miniclippt.com/live/v7/1006/south_korea_hi.png -O south\ korea.png
wget configs-web.agario.miniclippt.com/live/v7/1006/japan_hi.png -O japan.png
wget configs-web.agario.miniclippt.com/live/v7/1006/united_kingdom_hi.png -O united\ kingdom.png
wget configs-web.agario.miniclippt.com/live/v7/1006/earth_hi.png -O earth.png
wget configs-web.agario.miniclippt.com/live/v7/1006/greece_hi.png -O greece.png
wget configs-web.agario.miniclippt.com/live/v7/1006/latvia_hi.png -O latvia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/lithuania_hi.png -O lithuania.png
wget configs-web.agario.miniclippt.com/live/v7/1006/estonia_hi.png -O estonia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/finland_hi.png -O finland.png
wget configs-web.agario.miniclippt.com/live/v7/1006/norway_hi.png -O norway.png
wget configs-web.agario.miniclippt.com/live/v7/1006/cia_hi.png -O cia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Maldives_hi.png -O maldives.png
wget configs-web.agario.miniclippt.com/live/v7/1006/austria_hi.png -O austria.png
wget configs-web.agario.miniclippt.com/live/v7/1006/nigeria_hi.png -O nigeria.png
wget configs-web.agario.miniclippt.com/live/v7/1006/reddit_hi.png -O reddit.png
wget configs-web.agario.miniclippt.com/live/v7/1006/yaranaika_hi.png -O yaranaika.png
wget configs-web.agario.miniclippt.com/live/v7/1006/9gag_hi.png -O 9gag.png
wget configs-web.agario.miniclippt.com/live/v7/1006/indiana_hi.png -O indiana.png
wget configs-web.agario.miniclippt.com/live/v7/1006/4chan_hi.png -O 4chan.png
wget configs-web.agario.miniclippt.com/live/v7/1006/italy_hi.png -O italy.png
wget configs-web.agario.miniclippt.com/live/v7/1006/bulgaria_hi.png -O bulgaria.png
wget configs-web.agario.miniclippt.com/live/v7/1006/2ch_hk_hi.png -O 2ch.hk.png
wget configs-web.agario.miniclippt.com/live/v7/1006/hong_kong_hi.png -O hong\ kong.png
wget configs-web.agario.miniclippt.com/live/v7/1006/portugal_hi.png -O portugal.png
wget configs-web.agario.miniclippt.com/live/v7/1006/jamaica_hi.png -O jamaica.png
wget configs-web.agario.miniclippt.com/live/v7/1006/mexico_hi.png -O mexico.png
wget configs-web.agario.miniclippt.com/live/v7/1006/sanik_hi.png -O sanik.png
wget configs-web.agario.miniclippt.com/live/v7/1006/switzerland_hi.png -O switzerland.png
wget configs-web.agario.miniclippt.com/live/v7/1006/croatia_hi.png -O croatia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/chile_hi.png -O chile.png
wget configs-web.agario.miniclippt.com/live/v7/1006/indonesia_hi.png -O indonesia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/bangladesh_hi.png -O bangladesh.png
wget configs-web.agario.miniclippt.com/live/v7/1006/thailand_hi.png -O thailand.png
wget configs-web.agario.miniclippt.com/live/v7/1006/iran_hi.png -O iran.png
wget configs-web.agario.miniclippt.com/live/v7/1006/iraq_hi.png -O iraq.png
wget configs-web.agario.miniclippt.com/live/v7/1006/peru_hi.png -O peru.png
wget configs-web.agario.miniclippt.com/live/v7/1006/moon_hi.png -O moon.png
wget configs-web.agario.miniclippt.com/live/v7/1006/botswana_hi.png -O botswana.png
wget configs-web.agario.miniclippt.com/live/v7/1006/bosnia_hi.png -O bosnia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/netherlands_hi.png -O netherlands.png
wget configs-web.agario.miniclippt.com/live/v7/1006/european_union_hi.png -O european\ union.png
wget configs-web.agario.miniclippt.com/live/v7/1006/taiwan_hi.png -O taiwan.png
wget configs-web.agario.miniclippt.com/live/v7/1006/pakistan_hi.png -O pakistan.png
wget configs-web.agario.miniclippt.com/live/v7/1006/hungary_hi.png -O hungary.png
wget configs-web.agario.miniclippt.com/live/v7/1006/qing_dynasty_hi.png -O qing\ dynasty.png
wget configs-web.agario.miniclippt.com/live/v7/1006/matriarchy_hi.png -O matriarchy.png
wget configs-web.agario.miniclippt.com/live/v7/1006/patriarchy_hi.png -O patriarchy.png
wget configs-web.agario.miniclippt.com/live/v7/1006/feminism_hi.png -O feminism.png
wget configs-web.agario.miniclippt.com/live/v7/1006/ireland_hi.png -O ireland.png
wget configs-web.agario.miniclippt.com/live/v7/1006/texas_hi.png -O texas.png
wget configs-web.agario.miniclippt.com/live/v7/1006/facepunch_hi.png -O facepunch.png
wget configs-web.agario.miniclippt.com/live/v7/1006/prodota_hi.png -O prodota.png
wget configs-web.agario.miniclippt.com/live/v7/1006/cambodia_hi.png -O cambodia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/steam_hi.png -O steam.png
wget configs-web.agario.miniclippt.com/live/v7/1006/piccolo_hi.png -O piccolo.png
wget configs-web.agario.miniclippt.com/live/v7/1006/ea_hi.png -O ea.png
wget configs-web.agario.miniclippt.com/live/v7/1006/india_hi.png -O india.png
wget configs-web.agario.miniclippt.com/live/v7/1006/denmark_hi.png -O denmark.png
wget configs-web.agario.miniclippt.com/live/v7/1006/quebec_hi.png -O quebec.png
wget configs-web.agario.miniclippt.com/live/v7/1006/ayy_lmao_hi.png -O ayy\ lmao.png
wget configs-web.agario.miniclippt.com/live/v7/1006/sealand_hi.png -O sealand.png
wget configs-web.agario.miniclippt.com/live/v7/1006/bait_hi.png -O bait.png
wget configs-web.agario.miniclippt.com/live/v7/1006/origin_hi.png -O origin.png
wget configs-web.agario.miniclippt.com/live/v7/1006/vinesauce_hi.png -O vinesauce.png
wget configs-web.agario.miniclippt.com/live/v7/1006/belgium_hi.png -O belgium.png
wget configs-web.agario.miniclippt.com/live/v7/1006/luxembourg_hi.png -O luxembourg.png
wget configs-web.agario.miniclippt.com/live/v7/1006/stussy_hi.png -O stussy.png
wget configs-web.agario.miniclippt.com/live/v7/1006/8ch_hi.png -O 8ch.png
wget configs-web.agario.miniclippt.com/live/v7/1006/argentina_hi.png -O argentina.png
wget configs-web.agario.miniclippt.com/live/v7/1006/scotland_hi.png -O scotland.png
wget configs-web.agario.miniclippt.com/live/v7/1006/sir_hi.png -O sir.png
wget configs-web.agario.miniclippt.com/live/v7/1006/romania_hi.png -O romania.png
wget configs-web.agario.miniclippt.com/live/v7/1006/wojak_hi.png -O wojak.png
wget configs-web.agario.miniclippt.com/live/v7/1006/doge_hi.png -O doge.png
wget configs-web.agario.miniclippt.com/live/v7/1006/nasa_hi.png -O nasa.png
wget configs-web.agario.miniclippt.com/live/v7/1006/byzantium_hi.png -O byzantium.png
wget configs-web.agario.miniclippt.com/live/v7/1006/french_kingdom_hi.png -O french\ kingdom.png
wget configs-web.agario.miniclippt.com/live/v7/1006/somalia_hi.png -O somalia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/turkey_hi.png -O turkey.png
wget configs-web.agario.miniclippt.com/live/v7/1006/mars_hi.png -O mars.png
wget configs-web.agario.miniclippt.com/live/v7/1006/pokerface_hi.png -O pokerface.png
wget configs-web.agario.miniclippt.com/live/v7/1006/irs_hi.png -O irs.png
wget configs-web.agario.miniclippt.com/live/v7/1006/receita_federal_hi.png -O receita\ federal.png
wget configs-web.agario.miniclippt.com/live/v7/1006/8_hi.png -O 8.png
wget configs-web.agario.miniclippt.com/live/v7/1006/tsipras_hi.png -O tsipras.png
wget configs-web.agario.miniclippt.com/live/v7/1006/berlusconi_hi.png -O berlusconi.png
wget configs-web.agario.miniclippt.com/live/v7/1006/blatter_hi.png -O blatter.png
wget configs-web.agario.miniclippt.com/live/v7/1006/boris_hi.png -O boris.png
wget configs-web.agario.miniclippt.com/live/v7/1006/bush_hi.png -O bush.png
wget configs-web.agario.miniclippt.com/live/v7/1006/cameron_hi.png -O cameron.png
wget configs-web.agario.miniclippt.com/live/v7/1006/chavez_hi.png -O chavez.png
wget configs-web.agario.miniclippt.com/live/v7/1006/clinton_hi.png -O clinton.png
wget configs-web.agario.miniclippt.com/live/v7/1006/cuba_hi.png -O cuba.png
wget configs-web.agario.miniclippt.com/live/v7/1006/dilma_hi.png -O dilma.png
wget configs-web.agario.miniclippt.com/live/v7/1006/fidel_hi.png -O fidel.png
wget configs-web.agario.miniclippt.com/live/v7/1006/hillary_hi.png -O hillary.png
wget configs-web.agario.miniclippt.com/live/v7/1006/hollande_hi.png -O hollande.png
wget configs-web.agario.miniclippt.com/live/v7/1006/merkel_hi.png -O merkel.png
wget configs-web.agario.miniclippt.com/live/v7/1006/obama_hi.png -O obama.png
wget configs-web.agario.miniclippt.com/live/v7/1006/palin_hi.png -O palin.png
wget configs-web.agario.miniclippt.com/live/v7/1006/putin_hi.png -O putin.png
wget configs-web.agario.miniclippt.com/live/v7/1006/queen_hi.png -O queen.png
wget configs-web.agario.miniclippt.com/live/v7/1006/trump_hi.png -O trump.png
wget configs-web.agario.miniclippt.com/live/v7/1006/venezuela_hi.png -O venezuela.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Colombia_hi.png -O colombia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Soccer_hi.png -O football.png
wget configs-web.agario.miniclippt.com/live/v7/1006/varoufakis_hi.png -O varoufakis.png
wget configs-web.agario.miniclippt.com/live/v7/1006/House_of_Cards_hi.png -O underwood.png
wget configs-web.agario.miniclippt.com/live/v7/1006/chaplin_hi.png -O chaplin.png
wget configs-web.agario.miniclippt.com/live/v7/1006/confederate_hi.png -O confederate.png
wget configs-web.agario.miniclippt.com/live/v7/1006/tumblr_hi.png -O tumblr.png
wget configs-web.agario.miniclippt.com/live/v7/1006/german_empire_hi.png -O german\ empire.png
wget configs-web.agario.miniclippt.com/live/v7/1006/satanist_hi.png -O satanist.png
wget configs-web.agario.miniclippt.com/live/v7/1006/kc_hi.png -O kc.png
wget configs-web.agario.miniclippt.com/live/v7/1006/tsarist_russia_hi.png -O tsarist\ russia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/stalin_hi.png -O stalin.png
wget configs-web.agario.miniclippt.com/live/v7/1006/prussia_hi.png -O prussia.png
wget configs-web.agario.miniclippt.com/live/v7/1006/imperial_japan_hi.png -O imperial\ japan.png
wget configs-web.agario.miniclippt.com/live/v7/1006/facebook_hi.png -O facebook.png
wget configs-web.agario.miniclippt.com/live/v7/1006/kim_jong_un_hi.png -O kim\ jong-un.png
wget configs-web.agario.miniclippt.com/live/v7/1006/birthday_cake_hi.png -O agario.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Yellow_hi.png -O Pika.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Blue_hi.png -O Squi.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Green_hi.png -O Bulba.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Red_hi.png -O Char.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Crystal_hi.png -O crystal.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Kristoffer_hi.png -O kristoffer.png
wget configs-web.agario.miniclippt.com/live/v7/1006/n0psa_hi.png -O n0psa.png
wget configs-web.agario.miniclippt.com/live/v7/1006/RayDay_hi.png -O rayday.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Sirius_hi.png -O sirius.png
wget configs-web.agario.miniclippt.com/live/v7/1006/TYT_hi.png -O tyt.png
wget configs-web.agario.miniclippt.com/live/v7/1006/Matjoy_hi.png -O matjoy.png
