wget configs-web.agario.miniclippt.com/live/v7/806/poland_hi.png -O poland.png
wget configs-web.agario.miniclippt.com/live/v7/806/usa_hi.png -O usa.png
wget configs-web.agario.miniclippt.com/live/v7/806/china_hi.png -O china.png
wget configs-web.agario.miniclippt.com/live/v7/806/russia_hi.png -O russia.png
wget configs-web.agario.miniclippt.com/live/v7/806/canada_hi.png -O canada.png
wget configs-web.agario.miniclippt.com/live/v7/806/australia_hi.png -O australia.png
wget configs-web.agario.miniclippt.com/live/v7/806/spain_hi.png -O spain.png
wget configs-web.agario.miniclippt.com/live/v7/806/brazil_hi.png -O brazil.png
wget configs-web.agario.miniclippt.com/live/v7/806/germany_hi.png -O germany.png
wget configs-web.agario.miniclippt.com/live/v7/806/ukraine_hi.png -O ukraine.png
wget configs-web.agario.miniclippt.com/live/v7/806/france_hi.png -O france.png
wget configs-web.agario.miniclippt.com/live/v7/806/sweden_hi.png -O sweden.png
wget configs-web.agario.miniclippt.com/live/v7/806/north_korea_hi.png -O north\ korea.png
wget configs-web.agario.miniclippt.com/live/v7/806/south_korea_hi.png -O south\ korea.png
wget configs-web.agario.miniclippt.com/live/v7/806/japan_hi.png -O japan.png
wget configs-web.agario.miniclippt.com/live/v7/806/united_kingdom_hi.png -O united\ kingdom.png
wget configs-web.agario.miniclippt.com/live/v7/806/earth_hi.png -O earth.png
wget configs-web.agario.miniclippt.com/live/v7/806/greece_hi.png -O greece.png
wget configs-web.agario.miniclippt.com/live/v7/806/latvia_hi.png -O latvia.png
wget configs-web.agario.miniclippt.com/live/v7/806/lithuania_hi.png -O lithuania.png
wget configs-web.agario.miniclippt.com/live/v7/806/estonia_hi.png -O estonia.png
wget configs-web.agario.miniclippt.com/live/v7/806/finland_hi.png -O finland.png
wget configs-web.agario.miniclippt.com/live/v7/806/norway_hi.png -O norway.png
wget configs-web.agario.miniclippt.com/live/v7/806/cia_hi.png -O cia.png
wget configs-web.agario.miniclippt.com/live/v7/806/Maldives_hi.png -O maldives.png
wget configs-web.agario.miniclippt.com/live/v7/806/austria_hi.png -O austria.png
wget configs-web.agario.miniclippt.com/live/v7/806/nigeria_hi.png -O nigeria.png
wget configs-web.agario.miniclippt.com/live/v7/806/reddit_hi.png -O reddit.png
wget configs-web.agario.miniclippt.com/live/v7/806/yaranaika_hi.png -O yaranaika.png
wget configs-web.agario.miniclippt.com/live/v7/806/9gag_hi.png -O 9gag.png
wget configs-web.agario.miniclippt.com/live/v7/806/indiana_hi.png -O indiana.png
wget configs-web.agario.miniclippt.com/live/v7/806/4chan_hi.png -O 4chan.png
wget configs-web.agario.miniclippt.com/live/v7/806/italy_hi.png -O italy.png
wget configs-web.agario.miniclippt.com/live/v7/806/bulgaria_hi.png -O bulgaria.png
wget configs-web.agario.miniclippt.com/live/v7/806/2ch_hk_hi.png -O 2ch.hk.png
wget configs-web.agario.miniclippt.com/live/v7/806/hong_kong_hi.png -O hong\ kong.png
wget configs-web.agario.miniclippt.com/live/v7/806/portugal_hi.png -O portugal.png
wget configs-web.agario.miniclippt.com/live/v7/806/jamaica_hi.png -O jamaica.png
wget configs-web.agario.miniclippt.com/live/v7/806/mexico_hi.png -O mexico.png
wget configs-web.agario.miniclippt.com/live/v7/806/sanik_hi.png -O sanik.png
wget configs-web.agario.miniclippt.com/live/v7/806/switzerland_hi.png -O switzerland.png
wget configs-web.agario.miniclippt.com/live/v7/806/croatia_hi.png -O croatia.png
wget configs-web.agario.miniclippt.com/live/v7/806/chile_hi.png -O chile.png
wget configs-web.agario.miniclippt.com/live/v7/806/indonesia_hi.png -O indonesia.png
wget configs-web.agario.miniclippt.com/live/v7/806/bangladesh_hi.png -O bangladesh.png
wget configs-web.agario.miniclippt.com/live/v7/806/thailand_hi.png -O thailand.png
wget configs-web.agario.miniclippt.com/live/v7/806/iran_hi.png -O iran.png
wget configs-web.agario.miniclippt.com/live/v7/806/iraq_hi.png -O iraq.png
wget configs-web.agario.miniclippt.com/live/v7/806/peru_hi.png -O peru.png
wget configs-web.agario.miniclippt.com/live/v7/806/moon_hi.png -O moon.png
wget configs-web.agario.miniclippt.com/live/v7/806/botswana_hi.png -O botswana.png
wget configs-web.agario.miniclippt.com/live/v7/806/bosnia_hi.png -O bosnia.png
wget configs-web.agario.miniclippt.com/live/v7/806/netherlands_hi.png -O netherlands.png
wget configs-web.agario.miniclippt.com/live/v7/806/european_union_hi.png -O european\ union.png
wget configs-web.agario.miniclippt.com/live/v7/806/taiwan_hi.png -O taiwan.png
wget configs-web.agario.miniclippt.com/live/v7/806/pakistan_hi.png -O pakistan.png
wget configs-web.agario.miniclippt.com/live/v7/806/hungary_hi.png -O hungary.png
wget configs-web.agario.miniclippt.com/live/v7/806/qing_dynasty_hi.png -O qing\ dynasty.png
wget configs-web.agario.miniclippt.com/live/v7/806/matriarchy_hi.png -O matriarchy.png
wget configs-web.agario.miniclippt.com/live/v7/806/patriarchy_hi.png -O patriarchy.png
wget configs-web.agario.miniclippt.com/live/v7/806/feminism_hi.png -O feminism.png
wget configs-web.agario.miniclippt.com/live/v7/806/ireland_hi.png -O ireland.png
wget configs-web.agario.miniclippt.com/live/v7/806/texas_hi.png -O texas.png
wget configs-web.agario.miniclippt.com/live/v7/806/facepunch_hi.png -O facepunch.png
wget configs-web.agario.miniclippt.com/live/v7/806/prodota_hi.png -O prodota.png
wget configs-web.agario.miniclippt.com/live/v7/806/cambodia_hi.png -O cambodia.png
wget configs-web.agario.miniclippt.com/live/v7/806/steam_hi.png -O steam.png
wget configs-web.agario.miniclippt.com/live/v7/806/piccolo_hi.png -O piccolo.png
wget configs-web.agario.miniclippt.com/live/v7/806/ea_hi.png -O ea.png
wget configs-web.agario.miniclippt.com/live/v7/806/india_hi.png -O india.png
wget configs-web.agario.miniclippt.com/live/v7/806/denmark_hi.png -O denmark.png
wget configs-web.agario.miniclippt.com/live/v7/806/quebec_hi.png -O quebec.png
wget configs-web.agario.miniclippt.com/live/v7/806/ayy_lmao_hi.png -O ayy\ lmao.png
wget configs-web.agario.miniclippt.com/live/v7/806/sealand_hi.png -O sealand.png
wget configs-web.agario.miniclippt.com/live/v7/806/bait_hi.png -O bait.png
wget configs-web.agario.miniclippt.com/live/v7/806/origin_hi.png -O origin.png
wget configs-web.agario.miniclippt.com/live/v7/806/vinesauce_hi.png -O vinesauce.png
wget configs-web.agario.miniclippt.com/live/v7/806/belgium_hi.png -O belgium.png
wget configs-web.agario.miniclippt.com/live/v7/806/luxembourg_hi.png -O luxembourg.png
wget configs-web.agario.miniclippt.com/live/v7/806/stussy_hi.png -O stussy.png
wget configs-web.agario.miniclippt.com/live/v7/806/8ch_hi.png -O 8ch.png
wget configs-web.agario.miniclippt.com/live/v7/806/argentina_hi.png -O argentina.png
wget configs-web.agario.miniclippt.com/live/v7/806/scotland_hi.png -O scotland.png
wget configs-web.agario.miniclippt.com/live/v7/806/sir_hi.png -O sir.png
wget configs-web.agario.miniclippt.com/live/v7/806/romania_hi.png -O romania.png
wget configs-web.agario.miniclippt.com/live/v7/806/wojak_hi.png -O wojak.png
wget configs-web.agario.miniclippt.com/live/v7/806/doge_hi.png -O doge.png
wget configs-web.agario.miniclippt.com/live/v7/806/nasa_hi.png -O nasa.png
wget configs-web.agario.miniclippt.com/live/v7/806/byzantium_hi.png -O byzantium.png
wget configs-web.agario.miniclippt.com/live/v7/806/french_kingdom_hi.png -O french\ kingdom.png
wget configs-web.agario.miniclippt.com/live/v7/806/somalia_hi.png -O somalia.png
wget configs-web.agario.miniclippt.com/live/v7/806/turkey_hi.png -O turkey.png
wget configs-web.agario.miniclippt.com/live/v7/806/mars_hi.png -O mars.png
wget configs-web.agario.miniclippt.com/live/v7/806/pokerface_hi.png -O pokerface.png
wget configs-web.agario.miniclippt.com/live/v7/806/irs_hi.png -O irs.png
wget configs-web.agario.miniclippt.com/live/v7/806/receita_federal_hi.png -O receita\ federal.png
wget configs-web.agario.miniclippt.com/live/v7/806/8_hi.png -O 8.png
wget configs-web.agario.miniclippt.com/live/v7/806/tsipras_hi.png -O tsipras.png
wget configs-web.agario.miniclippt.com/live/v7/806/berlusconi_hi.png -O berlusconi.png
wget configs-web.agario.miniclippt.com/live/v7/806/blatter_hi.png -O blatter.png
wget configs-web.agario.miniclippt.com/live/v7/806/boris_hi.png -O boris.png
wget configs-web.agario.miniclippt.com/live/v7/806/bush_hi.png -O bush.png
wget configs-web.agario.miniclippt.com/live/v7/806/cameron_hi.png -O cameron.png
wget configs-web.agario.miniclippt.com/live/v7/806/chavez_hi.png -O chavez.png
wget configs-web.agario.miniclippt.com/live/v7/806/clinton_hi.png -O clinton.png
wget configs-web.agario.miniclippt.com/live/v7/806/cuba_hi.png -O cuba.png
wget configs-web.agario.miniclippt.com/live/v7/806/dilma_hi.png -O dilma.png
wget configs-web.agario.miniclippt.com/live/v7/806/fidel_hi.png -O fidel.png
wget configs-web.agario.miniclippt.com/live/v7/806/hillary_hi.png -O hillary.png
wget configs-web.agario.miniclippt.com/live/v7/806/hollande_hi.png -O hollande.png
wget configs-web.agario.miniclippt.com/live/v7/806/merkel_hi.png -O merkel.png
wget configs-web.agario.miniclippt.com/live/v7/806/obama_hi.png -O obama.png
wget configs-web.agario.miniclippt.com/live/v7/806/palin_hi.png -O palin.png
wget configs-web.agario.miniclippt.com/live/v7/806/putin_hi.png -O putin.png
wget configs-web.agario.miniclippt.com/live/v7/806/queen_hi.png -O queen.png
wget configs-web.agario.miniclippt.com/live/v7/806/trump_hi.png -O trump.png
wget configs-web.agario.miniclippt.com/live/v7/806/venezuela_hi.png -O venezuela.png
wget configs-web.agario.miniclippt.com/live/v7/806/Colombia_hi.png -O colombia.png
wget configs-web.agario.miniclippt.com/live/v7/806/Soccer_hi.png -O football.png
wget configs-web.agario.miniclippt.com/live/v7/806/varoufakis_hi.png -O varoufakis.png
wget configs-web.agario.miniclippt.com/live/v7/806/House_of_Cards_hi.png -O underwood.png
wget configs-web.agario.miniclippt.com/live/v7/806/chaplin_hi.png -O chaplin.png
wget configs-web.agario.miniclippt.com/live/v7/806/confederate_hi.png -O confederate.png
wget configs-web.agario.miniclippt.com/live/v7/806/tumblr_hi.png -O tumblr.png
wget configs-web.agario.miniclippt.com/live/v7/806/german_empire_hi.png -O german\ empire.png
wget configs-web.agario.miniclippt.com/live/v7/806/satanist_hi.png -O satanist.png
wget configs-web.agario.miniclippt.com/live/v7/806/kc_hi.png -O kc.png
wget configs-web.agario.miniclippt.com/live/v7/806/tsarist_russia_hi.png -O tsarist\ russia.png
wget configs-web.agario.miniclippt.com/live/v7/806/stalin_hi.png -O stalin.png
wget configs-web.agario.miniclippt.com/live/v7/806/prussia_hi.png -O prussia.png
wget configs-web.agario.miniclippt.com/live/v7/806/imperial_japan_hi.png -O imperial\ japan.png
wget configs-web.agario.miniclippt.com/live/v7/806/facebook_hi.png -O facebook.png
wget configs-web.agario.miniclippt.com/live/v7/806/kim_jong_un_hi.png -O kim\ jong-un.png
wget configs-web.agario.miniclippt.com/live/v7/806/birthday_cake_hi.png -O agario.png
wget configs-web.agario.miniclippt.com/live/v7/806/Yellow_hi.png -O Pika.png
wget configs-web.agario.miniclippt.com/live/v7/806/Blue_hi.png -O Squi.png
wget configs-web.agario.miniclippt.com/live/v7/806/Green_hi.png -O Bulba.png
wget configs-web.agario.miniclippt.com/live/v7/806/Red_hi.png -O Char.png
wget configs-web.agario.miniclippt.com/live/v7/806/Crystal_hi.png -O crystal.png
wget configs-web.agario.miniclippt.com/live/v7/806/Kristoffer_hi.png -O kristoffer.png
wget configs-web.agario.miniclippt.com/live/v7/806/n0psa_hi.png -O n0psa.png
wget configs-web.agario.miniclippt.com/live/v7/806/RayDay_hi.png -O rayday.png
wget configs-web.agario.miniclippt.com/live/v7/806/Sirius_hi.png -O sirius.png
wget configs-web.agario.miniclippt.com/live/v7/806/TYT_hi.png -O tyt.png
wget configs-web.agario.miniclippt.com/live/v7/806/Matjoy_hi.png -O matjoy.png
