wget configs-web.agario.miniclippt.com/live/v5/474/Banana_hi.png -O banana.png
wget configs-web.agario.miniclippt.com/live/v5/474/Cookie_hi.png -O cookie.png
wget configs-web.agario.miniclippt.com/live/v5/474/Jupiter_hi.png -O jupiter.png
wget configs-web.agario.miniclippt.com/live/v5/474/Birdie_hi.png -O birdie.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mercury_hi.png -O mercury.png
wget configs-web.agario.miniclippt.com/live/v5/474/Apple_hi.png -O apple.png
wget configs-web.agario.miniclippt.com/live/v5/474/Good_hi.png -O good.png
wget configs-web.agario.miniclippt.com/live/v5/474/Neptune_hi.png -O neptune.png
wget configs-web.agario.miniclippt.com/live/v5/474/Blackhole_hi.png -O blackhole.png
wget configs-web.agario.miniclippt.com/live/v5/474/Uranus_hi.png -O uranus.png
wget configs-web.agario.miniclippt.com/live/v5/474/Starball_hi.png -O starball.png
wget configs-web.agario.miniclippt.com/live/v5/474/Target_hi.png -O target.png
wget configs-web.agario.miniclippt.com/live/v5/474/Galaxy_hi.png -O galaxy.png
wget configs-web.agario.miniclippt.com/live/v5/474/Venus_hi.png -O venus.png
wget configs-web.agario.miniclippt.com/live/v5/474/Breakfast_hi.png -O breakfast.png
wget configs-web.agario.miniclippt.com/live/v5/474/Saturn_hi.png -O saturn.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pluto_hi.png -O pluto.png
wget configs-web.agario.miniclippt.com/live/v5/474/Tiger_Pattern_hi.png -O tigerpattern.png
wget configs-web.agario.miniclippt.com/live/v5/474/Hot_Dog_hi.png -O hotdog.png
wget configs-web.agario.miniclippt.com/live/v5/474/Heart_hi.png -O heart.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mouse_hi.png -O mouse.png
wget configs-web.agario.miniclippt.com/live/v5/474/Wolf_hi.png -O wolf.png
wget configs-web.agario.miniclippt.com/live/v5/474/Goldfish_hi.png -O goldfish.png
wget configs-web.agario.miniclippt.com/live/v5/474/pig_hi.png -O pig.png
wget configs-web.agario.miniclippt.com/live/v5/474/Blueberry_Face_hi.png -O blueberry.png
wget configs-web.agario.miniclippt.com/live/v5/474/Bomb_hi.png -O bomb.png
wget configs-web.agario.miniclippt.com/live/v5/474/Bowling_hi.png -O bowling.png
wget configs-web.agario.miniclippt.com/live/v5/474/Candy_hi.png -O candy.png
wget configs-web.agario.miniclippt.com/live/v5/474/Frog_hi.png -O frog.png
wget configs-web.agario.miniclippt.com/live/v5/474/Hamburguer_hi.png -O hamburguer.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nose_hi.png -O nose.png
wget configs-web.agario.miniclippt.com/live/v5/474/Seal_hi.png -O seal.png
wget configs-web.agario.miniclippt.com/live/v5/474/Panda_hi.png -O panda.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pizza_hi.png -O pizza.png
wget configs-web.agario.miniclippt.com/live/v5/474/Snowman_hi.png -O snowman.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sun_hi.png -O sun.png
wget configs-web.agario.miniclippt.com/live/v5/474/Baseball_hi.png -O baseball.png
wget configs-web.agario.miniclippt.com/live/v5/474/Basketball_hi.png -O basketball.png
wget configs-web.agario.miniclippt.com/live/v5/474/Bug_hi.png -O bug.png
wget configs-web.agario.miniclippt.com/live/v5/474/Cloud_hi.png -O cloud.png
wget configs-web.agario.miniclippt.com/live/v5/474/Muu_hi.png -O muu.png
wget configs-web.agario.miniclippt.com/live/v5/474/Tomato_Face_hi.png -O tomatoface.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mushroom_hi.png -O mushroom.png
wget configs-web.agario.miniclippt.com/live/v5/474/Donuts_hi.png -O donuts.png
wget configs-web.agario.miniclippt.com/live/v5/474/Terrible_hi.png -O terrible.png
wget configs-web.agario.miniclippt.com/live/v5/474/ghost_hi.png -O ghost.png
wget configs-web.agario.miniclippt.com/live/v5/474/Apple_Face_hi.png -O appleface.png
wget configs-web.agario.miniclippt.com/live/v5/474/Turtle_hi.png -O turtle.png
wget configs-web.agario.miniclippt.com/live/v5/474/BroFist_hi.png -O brofist.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dog_hi.png -O dog.png
wget configs-web.agario.miniclippt.com/live/v5/474/FootPrint_hi.png -O footprint.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pineapple_Face_hi.png -O pineappleface.png
wget configs-web.agario.miniclippt.com/live/v5/474/Zebra_Pattern_hi.png -O zebrapattern.png
wget configs-web.agario.miniclippt.com/live/v5/474/toon_hi.png -O toon.png
wget configs-web.agario.miniclippt.com/live/v5/474/Octopus_hi.png -O octopus.png
wget configs-web.agario.miniclippt.com/live/v5/474/Radar_hi.png -O radar.png
wget configs-web.agario.miniclippt.com/live/v5/474/Eye_hi.png -O eye.png
wget configs-web.agario.miniclippt.com/live/v5/474/Owl_hi.png -O owl.png
wget configs-web.agario.miniclippt.com/live/v5/474/Virus_hi.png -O virus.png
wget configs-web.agario.miniclippt.com/live/v5/474/smile_hi.png -O smile.png
wget configs-web.agario.miniclippt.com/live/v5/474/Army_hi.png -O army.png
wget configs-web.agario.miniclippt.com/live/v5/474/Cat_hi.png -O cat.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nuclear_hi.png -O nuclear.png
wget configs-web.agario.miniclippt.com/live/v5/474/Toxic_hi.png -O toxic.png
wget configs-web.agario.miniclippt.com/live/v5/474/Doggie_hi.png -O doggie.png
wget configs-web.agario.miniclippt.com/live/v5/474/face_hi.png -O face.png
wget configs-web.agario.miniclippt.com/live/v5/474/Willie_hi.png -O willie.png
wget configs-web.agario.miniclippt.com/live/v5/474/Luchador_hi.png -O luchador.png
wget configs-web.agario.miniclippt.com/live/v5/474/zombie_hi.png -O zombie.png
wget configs-web.agario.miniclippt.com/live/v5/474/Bite_hi.png -O bite.png
wget configs-web.agario.miniclippt.com/live/v5/474/Crazy_hi.png -O crazy.png
wget configs-web.agario.miniclippt.com/live/v5/474/Hockey_hi.png -O hockey.png
wget configs-web.agario.miniclippt.com/live/v5/474/Jar_Brain_hi.png -O jarbrain.png
wget configs-web.agario.miniclippt.com/live/v5/474/Evil_hi.png -O evil.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pirate_hi.png -O pirate.png
wget configs-web.agario.miniclippt.com/live/v5/474/evil_eye_hi.png -O evileye.png
wget configs-web.agario.miniclippt.com/live/v5/474/Halloween_hi.png -O halloween.png
wget configs-web.agario.miniclippt.com/live/v5/474/Monster_hi.png -O monster.png
wget configs-web.agario.miniclippt.com/live/v5/474/Scarecrow_hi.png -O scarecrow.png
wget configs-web.agario.miniclippt.com/live/v5/474/Spy_hi.png -O spy.png
wget configs-web.agario.miniclippt.com/live/v5/474/X-mas_hi.png -O santa.png
wget configs-web.agario.miniclippt.com/live/v5/474/GingerBreadMan_hi.png -O gingerbread.png
wget configs-web.agario.miniclippt.com/live/v5/474/Grinch_hi.png -O grinch.png
wget configs-web.agario.miniclippt.com/live/v5/474/Fly_hi.png -O fly.png
wget configs-web.agario.miniclippt.com/live/v5/474/Spider_hi.png -O spider.png
wget configs-web.agario.miniclippt.com/live/v5/474/Wasp_hi.png -O wasp.png
wget configs-web.agario.miniclippt.com/live/v5/474/Lizard_hi.png -O lizard.png
wget configs-web.agario.miniclippt.com/live/v5/474/Bat_hi.png -O bat.png
wget configs-web.agario.miniclippt.com/live/v5/474/Snake_hi.png -O snake.png
wget configs-web.agario.miniclippt.com/live/v5/474/Fox_hi.png -O fox.png
wget configs-web.agario.miniclippt.com/live/v5/474/Coyote_hi.png -O coyote.png
wget configs-web.agario.miniclippt.com/live/v5/474/Hunter_hi.png -O hunter.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sumo_hi.png -O sumo.png
wget configs-web.agario.miniclippt.com/live/v5/474/Bear_hi.png -O bear.png
wget configs-web.agario.miniclippt.com/live/v5/474/Cougar_hi.png -O cougar.png
wget configs-web.agario.miniclippt.com/live/v5/474/Panther_hi.png -O panther.png
wget configs-web.agario.miniclippt.com/live/v5/474/Lion_hi.png -O lion.png
wget configs-web.agario.miniclippt.com/live/v5/474/Crocodile_hi.png -O crocodile.png
wget configs-web.agario.miniclippt.com/live/v5/474/Shark_hi.png -O shark.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mammoth_hi.png -O mammoth.png
wget configs-web.agario.miniclippt.com/live/v5/474/Raptor_hi.png -O raptor.png
wget configs-web.agario.miniclippt.com/live/v5/474/T-Rex_hi.png -O t_rex.png
wget configs-web.agario.miniclippt.com/live/v5/474/Kraken_hi.png -O kraken.png
wget configs-web.agario.miniclippt.com/live/v5/474/CupCake_hi.png -O cupcake.png
wget configs-web.agario.miniclippt.com/live/v5/474/KissBoy_hi.png -O kiss_boy.png
wget configs-web.agario.miniclippt.com/live/v5/474/KissGirl_hi.png -O kiss_girl.png
wget configs-web.agario.miniclippt.com/live/v5/474/Cupid_hi.png -O cupid.png
wget configs-web.agario.miniclippt.com/live/v5/474/Shuttle_hi.png -O shuttle.png
wget configs-web.agario.miniclippt.com/live/v5/474/Astronaut_hi.png -O astronaut.png
wget configs-web.agario.miniclippt.com/live/v5/474/Laika_hi.png -O space_dog.png
wget configs-web.agario.miniclippt.com/live/v5/474/Grey_hi.png -O grey.png
wget configs-web.agario.miniclippt.com/live/v5/474/Comet_hi.png -O meteor.png
wget configs-web.agario.miniclippt.com/live/v5/474/UFO_hi.png -O ufo.png
wget configs-web.agario.miniclippt.com/live/v5/474/Rocket_hi.png -O rocket.png
wget configs-web.agario.miniclippt.com/live/v5/474/Boot_hi.png -O boot.png
wget configs-web.agario.miniclippt.com/live/v5/474/Gold_Pot_hi.png -O gold_pot.png
wget configs-web.agario.miniclippt.com/live/v5/474/Hat_hi.png -O hat.png
wget configs-web.agario.miniclippt.com/live/v5/474/Horse_Shoe_hi.png -O horse_shoe.png
wget configs-web.agario.miniclippt.com/live/v5/474/Leaf_Clover_hi.png -O leaf_clover.png
wget configs-web.agario.miniclippt.com/live/v5/474/Leprechaun_hi.png -O leprechaun.png
wget configs-web.agario.miniclippt.com/live/v5/474/Rainbow_hi.png -O rainbow.png
wget configs-web.agario.miniclippt.com/live/v5/474/Choco_Egg_hi.png -O choco_egg.png
wget configs-web.agario.miniclippt.com/live/v5/474/Carrot_hi.png -O carrot.png
wget configs-web.agario.miniclippt.com/live/v5/474/Easter_Island_hi.png -O easter_island.png
wget configs-web.agario.miniclippt.com/live/v5/474/Rooster_hi.png -O rooster.png
wget configs-web.agario.miniclippt.com/live/v5/474/Rabbit_hi.png -O rabbit.png
wget configs-web.agario.miniclippt.com/live/v5/474/AprilFool_hi.png -O april_fool.png
wget configs-web.agario.miniclippt.com/live/v5/474/EarthDay_hi.png -O earth_day.png
wget configs-web.agario.miniclippt.com/live/v5/474/Chihuahua_hi.png -O chihuahua.png
wget configs-web.agario.miniclippt.com/live/v5/474/Cactus_hi.png -O cactus.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sombrero_hi.png -O sombrero.png
wget configs-web.agario.miniclippt.com/live/v5/474/ChilliPepper_hi.png -O hot_pepper.png
wget configs-web.agario.miniclippt.com/live/v5/474/ChupaCabra_hi.png -O chupacabra.png
wget configs-web.agario.miniclippt.com/live/v5/474/Tortilha_hi.png -O taco.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pinhata_hi.png -O pinata.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dragon_hi.png -O dragon.png
wget configs-web.agario.miniclippt.com/live/v5/474/Gargoyle_hi.png -O gargoyle.png
wget configs-web.agario.miniclippt.com/live/v5/474/Gopher_hi.png -O gopher.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sheep_hi.png -O sheep.png
wget configs-web.agario.miniclippt.com/live/v5/474/Thirteen_hi.png -O thirteen.png
wget configs-web.agario.miniclippt.com/live/v5/474/BlackCat_hi.png -O black_cat.png
wget configs-web.agario.miniclippt.com/live/v5/474/Crow_hi.png -O crow.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mask_hi.png -O mask.png
wget configs-web.agario.miniclippt.com/live/v5/474/Witch_hi.png -O goblin.png
wget configs-web.agario.miniclippt.com/live/v5/474/GreenMan_hi.png -O greenman.png
wget configs-web.agario.miniclippt.com/live/v5/474/SlimeFace_hi.png -O slimeface.png
wget configs-web.agario.miniclippt.com/live/v5/474/JellyBlob_hi.png -O jellyblob.png
wget configs-web.agario.miniclippt.com/live/v5/474/AlienX_hi.png -O invader.png
wget configs-web.agario.miniclippt.com/live/v5/474/SpaceHunter_hi.png -O spacehunter.png
wget configs-web.agario.miniclippt.com/live/v5/474/Soccer_Ball_hi.png -O soccerball.png
wget configs-web.agario.miniclippt.com/live/v5/474/Glub_hi.png -O glub.png
wget configs-web.agario.miniclippt.com/live/v5/474/Soccer_Shoe_hi.png -O soccer_shoe.png
wget configs-web.agario.miniclippt.com/live/v5/474/Player_2_hi.png -O striker.png
wget configs-web.agario.miniclippt.com/live/v5/474/Player_1_hi.png -O starplayer.png
wget configs-web.agario.miniclippt.com/live/v5/474/TenderHeart_Bear_hi.png -O tender_heart_bear.png
wget configs-web.agario.miniclippt.com/live/v5/474/FunShine_Bear_hi.png -O funshine_bear.png
wget configs-web.agario.miniclippt.com/live/v5/474/BrightHeart_Racoon_hi.png -O bright_heart_raccoon.png
wget configs-web.agario.miniclippt.com/live/v5/474/CozyHeart_Penguin_hi.png -O cozy_heart_penguin.png
wget configs-web.agario.miniclippt.com/live/v5/474/LotsaHeart_Elephant_hi.png -O lotsa_heart_elephant.png
wget configs-web.agario.miniclippt.com/live/v5/474/BraveHeart_Lion_hi.png -O brave_heart_lion.png
wget configs-web.agario.miniclippt.com/live/v5/474/Crazy_Ball_hi.png -O crazy_ball.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sky_Rocket_hi.png -O skyrocket.png
wget configs-web.agario.miniclippt.com/live/v5/474/Stars_and_Stripes_hi.png -O stars_stripes.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mighty_hi.png -O mighty.png
wget configs-web.agario.miniclippt.com/live/v5/474/Uncle_Sam_hi.png -O uncle_sam.png
wget configs-web.agario.miniclippt.com/live/v5/474/Eagle_hi.png -O eagle.png
wget configs-web.agario.miniclippt.com/live/v5/474/Liberty_hi.png -O liberty.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mummy_Ball_hi.png -O dust_brain.png
wget configs-web.agario.miniclippt.com/live/v5/474/Eye_Ball_hi.png -O oculus_orbus.png
wget configs-web.agario.miniclippt.com/live/v5/474/BaseballSmile_Ball_hi.png -O screamin_meamie.png
wget configs-web.agario.miniclippt.com/live/v5/474/Cyclop_Ball_hi.png -O hornhead.png
wget configs-web.agario.miniclippt.com/live/v5/474/SkullBrain_Ball_hi.png -O skull_face.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sunbath_hi.png -O sunbath.png
wget configs-web.agario.miniclippt.com/live/v5/474/Watermelon_hi.png -O watermelon.png
wget configs-web.agario.miniclippt.com/live/v5/474/StarFish_hi.png -O starfish.png
wget configs-web.agario.miniclippt.com/live/v5/474/IcecreamFace_hi.png -O icecream.png
wget configs-web.agario.miniclippt.com/live/v5/474/Surfer_hi.png -O surfer.png
wget configs-web.agario.miniclippt.com/live/v5/474/Diver_hi.png -O diver.png
wget configs-web.agario.miniclippt.com/live/v5/474/birthday_sanik_hi.png -O birthday_sanik.png
wget configs-web.agario.miniclippt.com/live/v5/474/birthday_wojak_hi.png -O birthday_wojak.png
wget configs-web.agario.miniclippt.com/live/v5/474/birthday_cia_hi.png -O birthday_cia.png
wget configs-web.agario.miniclippt.com/live/v5/474/birthday_sir_hi.png -O birthday_sir.png
wget configs-web.agario.miniclippt.com/live/v5/474/birthday_doge_hi.png -O birthday_doge.png
wget configs-web.agario.miniclippt.com/live/v5/474/birthday_lol_hi.png -O birthday_lol.png
wget configs-web.agario.miniclippt.com/live/v5/474/birthday_troll_hi.png -O birthday_troll.png
wget configs-web.agario.miniclippt.com/live/v5/474/food_Cofee_hi.png -O hot_coffee.png
wget configs-web.agario.miniclippt.com/live/v5/474/food_Juice_Can_hi.png -O soda_can.png
wget configs-web.agario.miniclippt.com/live/v5/474/food_Jelly_Face_hi.png -O jelly.png
wget configs-web.agario.miniclippt.com/live/v5/474/food_French_Fries_hi.png -O fries.png
wget configs-web.agario.miniclippt.com/live/v5/474/food_Hamburguer_hi.png -O burger_face.png
wget configs-web.agario.miniclippt.com/live/v5/474/food_Terminita_hi.png -O hard_shroom.png
wget configs-web.agario.miniclippt.com/live/v5/474/food_Chicken_Leg_hi.png -O drumstick.png
wget configs-web.agario.miniclippt.com/live/v5/474/rio_tennis_hi.png -O tennist.png
wget configs-web.agario.miniclippt.com/live/v5/474/rio_gymnastic_hi.png -O gymnast.png
wget configs-web.agario.miniclippt.com/live/v5/474/rio_judo_hi.png -O judo_fighter.png
wget configs-web.agario.miniclippt.com/live/v5/474/rio_swimmer_hi.png -O swimmer.png
wget configs-web.agario.miniclippt.com/live/v5/474/rio_athletic_hi.png -O sprinter.png
wget configs-web.agario.miniclippt.com/live/v5/474/rio_mico_hi.png -O mico.png
wget configs-web.agario.miniclippt.com/live/v5/474/rio_toco_hi.png -O toco.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pirates_Parrot_hi.png -O parrot.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pirates_Rascal_hi.png -O rascal.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pirates_PirateGirl_hi.png -O pirate_maiden.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pirates_SkullPirate_hi.png -O captain_skull.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pirates_Captain_hi.png -O black_beard.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pirates_CannonBall_hi.png -O cannonball.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pirates_Monkey_hi.png -O mad_monkey.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sports_Target_hi.png -O bullseye.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sports_Fencing_hi.png -O touche.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sports_BoxingGlub_hi.png -O jab.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sports_Golf_hi.png -O backswing.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sports_Volleyball_hi.png -O spike.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sports_PingPong_hi.png -O smash.png
wget configs-web.agario.miniclippt.com/live/v5/474/Sports_Basketball_hi.png -O dunk.png
wget configs-web.agario.miniclippt.com/live/v5/474/Alien2_Gamma_hi.png -O gamma.png
wget configs-web.agario.miniclippt.com/live/v5/474/Alien2_Neila_hi.png -O neila.png
wget configs-web.agario.miniclippt.com/live/v5/474/Alien2_Omicron_hi.png -O omicron.png
wget configs-web.agario.miniclippt.com/live/v5/474/Alien2_Vega_hi.png -O vega.png
wget configs-web.agario.miniclippt.com/live/v5/474/Alien2_Smyg_hi.png -O smyg.png
wget configs-web.agario.miniclippt.com/live/v5/474/Journey_WhiteHorse_hi.png -O white_horse.png
wget configs-web.agario.miniclippt.com/live/v5/474/Journey_Monk_hi.png -O monk.png
wget configs-web.agario.miniclippt.com/live/v5/474/Journey_WaterSpirit_hi.png -O water_spirit.png
wget configs-web.agario.miniclippt.com/live/v5/474/Journey_Boar_hi.png -O boar.png
wget configs-web.agario.miniclippt.com/live/v5/474/Journey_Kong_hi.png -O kong.png
wget configs-web.agario.miniclippt.com/live/v5/474/Journey_BullKing_hi.png -O bull_king.png
wget configs-web.agario.miniclippt.com/live/v5/474/Journey_JadeDragon_hi.png -O jade_dragon.png
wget configs-web.agario.miniclippt.com/live/v5/474/Treasure_Squiggly_hi.png -O treasure_squiggly.png
wget configs-web.agario.miniclippt.com/live/v5/474/Treasure_SeaExplorer_hi.png -O treasure_explorer.png
wget configs-web.agario.miniclippt.com/live/v5/474/Autumn_Squirrel_hi.png -O squirrel.png
wget configs-web.agario.miniclippt.com/live/v5/474/Autumn_Acorn_hi.png -O acorn.png
wget configs-web.agario.miniclippt.com/live/v5/474/Autumn_Maple_hi.png -O maple.png
wget configs-web.agario.miniclippt.com/live/v5/474/Autumn_Badger_hi.png -O badger.png
wget configs-web.agario.miniclippt.com/live/v5/474/Autumn_Prey_hi.png -O prey.png
wget configs-web.agario.miniclippt.com/live/v5/474/Autumn_Sly_hi.png -O sly.png
wget configs-web.agario.miniclippt.com/live/v5/474/Autumn_Faun_hi.png -O faun.png
wget configs-web.agario.miniclippt.com/live/v5/474/Island_Pinehead_hi.png -O pinehead.png
wget configs-web.agario.miniclippt.com/live/v5/474/Island_Sea_Turtle_hi.png -O sea_turtle.png
wget configs-web.agario.miniclippt.com/live/v5/474/Island_Volcano_hi.png -O volcano.png
wget configs-web.agario.miniclippt.com/live/v5/474/Island_Coconuts_hi.png -O coconuts.png
wget configs-web.agario.miniclippt.com/live/v5/474/Island_Warrior_hi.png -O warrior.png
wget configs-web.agario.miniclippt.com/live/v5/474/Island_Seer_hi.png -O seer.png
wget configs-web.agario.miniclippt.com/live/v5/474/Island_Scar_hi.png -O scar.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dead_Viper_hi.png -O viper.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dead_Biker_hi.png -O biker.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dead_DesertFox_hi.png -O desert_fox.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dead_Ranger_hi.png -O ranger.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dead_Devourer_hi.png -O devourer.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dead_Raider_hi.png -O raider.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dead_Nuke_hi.png -O nuke.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nuclear_ToxicEater_hi.png -O toxic_eater.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nuclear_Ogre_hi.png -O ogre.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nuclear_Scavenger_hi.png -O scavenger.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nuclear_Marauder_hi.png -O marauder.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nuclear_Mutant_hi.png -O mutant.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nuclear_Ooze_hi.png -O ooze.png
wget configs-web.agario.miniclippt.com/live/v5/474/Nuclear_Hazmat_hi.png -O hazmat.png
wget configs-web.agario.miniclippt.com/live/v5/474/HappyWeekend_Croc_hi.png -O happy_croc.png
wget configs-web.agario.miniclippt.com/live/v5/474/Undead_hi.png -O undead.png
wget configs-web.agario.miniclippt.com/live/v5/474/Phantom_hi.png -O phantom.png
wget configs-web.agario.miniclippt.com/live/v5/474/Werewolf_hi.png -O werewolf.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mummy_hi.png -O mummy.png
wget configs-web.agario.miniclippt.com/live/v5/474/Vampire_hi.png -O vampire.png
wget configs-web.agario.miniclippt.com/live/v5/474/Frankenstein_hi.png -O frankenstein.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pumpkin_hi.png -O pumpkin.png
wget configs-web.agario.miniclippt.com/live/v5/474/Masked_hi.png -O masked.png
wget configs-web.agario.miniclippt.com/live/v5/474/Skull_Cactus_hi.png -O skull_cactus.png
wget configs-web.agario.miniclippt.com/live/v5/474/Skeleton_hi.png -O skeleton.png
wget configs-web.agario.miniclippt.com/live/v5/474/Infernando_hi.png -O infernando.png
wget configs-web.agario.miniclippt.com/live/v5/474/Calavera_hi.png -O calavera.png
wget configs-web.agario.miniclippt.com/live/v5/474/Poison_Rose_hi.png -O poison_rose.png
wget configs-web.agario.miniclippt.com/live/v5/474/Calaca_hi.png -O calaca.png
wget configs-web.agario.miniclippt.com/live/v5/474/SH_MajorEagle_hi.png -O major_eagle.png
wget configs-web.agario.miniclippt.com/live/v5/474/SH_X_Ray_hi.png -O xray.png
wget configs-web.agario.miniclippt.com/live/v5/474/SH_TigerMan_hi.png -O the_tiger.png
wget configs-web.agario.miniclippt.com/live/v5/474/SH_StarGirl_hi.png -O star_sentinel.png
wget configs-web.agario.miniclippt.com/live/v5/474/SH_IronKnight_hi.png -O iron_titan.png
wget configs-web.agario.miniclippt.com/live/v5/474/SH_ArachnoKid_hi.png -O cyber_kid.png
wget configs-web.agario.miniclippt.com/live/v5/474/SH_OmegaBlast_hi.png -O omega_blast.png
wget configs-web.agario.miniclippt.com/live/v5/474/SH_DrCosmos_hi.png -O dr_cosmos.png
wget configs-web.agario.miniclippt.com/live/v5/474/Terra_hi.png -O terra.png
wget configs-web.agario.miniclippt.com/live/v5/474/Aqua_hi.png -O aqua.png
wget configs-web.agario.miniclippt.com/live/v5/474/Aer_hi.png -O aer.png
wget configs-web.agario.miniclippt.com/live/v5/474/Ignis_hi.png -O ignis.png
wget configs-web.agario.miniclippt.com/live/v5/474/Colossus_hi.png -O colossus.png
wget configs-web.agario.miniclippt.com/live/v5/474/Dark_Matter_hi.png -O dark_matter.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pie_Slice_hi.png -O pie_slice.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pilgrim_hi.png -O pilgrim.png
wget configs-web.agario.miniclippt.com/live/v5/474/Virginia_hi.png -O virginia.png
wget configs-web.agario.miniclippt.com/live/v5/474/Thanksgiving_Turkey_hi.png -O turkey.png
wget configs-web.agario.miniclippt.com/live/v5/474/Mr_Pumpkin_hi.png -O mr_pumpkin.png
wget configs-web.agario.miniclippt.com/live/v5/474/Happy_hi.png -O happy.png
wget configs-web.agario.miniclippt.com/live/v5/474/Bread_hi.png -O bread.png
wget configs-web.agario.miniclippt.com/live/v5/474/Pug_hi.png -O pug.png
wget configs-web.agario.miniclippt.com/live/v5/474/Winter_Wolf_hi.png -O winter_wolf.png
wget configs-web.agario.miniclippt.com/live/v5/474/Viking_hi.png -O viking.png
wget configs-web.agario.miniclippt.com/live/v5/474/Icy_Braid_hi.png -O icy_braid.png
wget configs-web.agario.miniclippt.com/live/v5/474/Berserker_hi.png -O berserker.png
wget configs-web.agario.miniclippt.com/live/v5/474/Champion_hi.png -O champion.png
wget configs-web.agario.miniclippt.com/live/v5/474/Jotun_hi.png -O jotun.png
wget configs-web.agario.miniclippt.com/live/v5/474/ArcheryKing_Skin_hi.png -O archery_king.png
wget configs-web.agario.miniclippt.com/live/v5/474/creatures_root_gnome_hi.png -O root_gnome.png
wget configs-web.agario.miniclippt.com/live/v5/474/creatures_hobgoblin_hi.png -O hobgoblin.png
wget configs-web.agario.miniclippt.com/live/v5/474/creatures_pixie_hi.png -O pixie.png
wget configs-web.agario.miniclippt.com/live/v5/474/creatures_basilisk_hi.png -O basilisk.png
wget configs-web.agario.miniclippt.com/live/v5/474/creatures_firebird_hi.png -O firebird.png
wget configs-web.agario.miniclippt.com/live/v5/474/creatures_magic_gerbil_hi.png -O magic_gerbil.png
wget configs-web.agario.miniclippt.com/live/v5/474/creatures_gryphon_hi.png -O gryphon.png
wget configs-web.agario.miniclippt.com/live/v5/474/creatures_dark_wings_hi.png -O dark_wings.png
wget configs-web.agario.miniclippt.com/live/v5/474/dawn_cyber_guard_hi.png -O cyber_guard.png
wget configs-web.agario.miniclippt.com/live/v5/474/dawn_star_pilot_hi.png -O star_pilot.png
wget configs-web.agario.miniclippt.com/live/v5/474/dawn_cosmo_pirate_hi.png -O cosmo_pirate.png
wget configs-web.agario.miniclippt.com/live/v5/474/dawn_moon_ship_hi.png -O moon_ship.png
wget configs-web.agario.miniclippt.com/live/v5/474/dawn_space_warden_hi.png -O space_warden.png
wget configs-web.agario.miniclippt.com/live/v5/474/dawn_evil_master_hi.png -O evil_master.png
wget configs-web.agario.miniclippt.com/live/v5/474/xmas_2016_reindeer_hi.png -O reindeer.png
wget configs-web.agario.miniclippt.com/live/v5/474/xmas_2016_elf_helper_hi.png -O elf_helper.png
wget configs-web.agario.miniclippt.com/live/v5/474/xmas_2016_santa_claus_hi.png -O santa_claus.png
wget configs-web.agario.miniclippt.com/live/v5/474/xmas_2016_polar_bear_hi.png -O polar_bear.png
wget configs-web.agario.miniclippt.com/live/v5/474/xmas_2016_penguin_hi.png -O penguin.png
wget configs-web.agario.miniclippt.com/live/v5/474/new_year_2016_flying_cork_hi.png -O flying_cork.png
wget configs-web.agario.miniclippt.com/live/v5/474/new_year_2016_happy_soda_hi.png -O happy_soda.png
wget configs-web.agario.miniclippt.com/live/v5/474/beast_fighters_goat_hi.png -O bruiser_goat.png
wget configs-web.agario.miniclippt.com/live/v5/474/beast_fighters_bunny_hi.png -O rogue_bunny.png
wget configs-web.agario.miniclippt.com/live/v5/474/beast_fighters_rhino_hi.png -O rhino_boxer.png
wget configs-web.agario.miniclippt.com/live/v5/474/beast_fighters_bull_hi.png -O street_bull.png
wget configs-web.agario.miniclippt.com/live/v5/474/beast_fighters_husky_hi.png -O husky_brawl.png
wget configs-web.agario.miniclippt.com/live/v5/474/beast_fighters_tiger_hi.png -O kempo_tiger.png
wget configs-web.agario.miniclippt.com/live/v5/474/time_travel_best_friends_hi.png -O best_friends.png
wget configs-web.agario.miniclippt.com/live/v5/474/time_travel_chrono_ranger_hi.png -O chrono_ranger.png
wget configs-web.agario.miniclippt.com/live/v5/474/time_travel_cool_agent_hi.png -O cool_agent.png
wget configs-web.agario.miniclippt.com/live/v5/474/time_travel_time_dude_hi.png -O time_dude.png
wget configs-web.agario.miniclippt.com/live/v5/474/time_travel_time_doctor_hi.png -O time_doctor.png
wget configs-web.agario.miniclippt.com/live/v5/474/friday_the_13th_2017_wicked_cat_hi.png -O wicked_cat.png
wget configs-web.agario.miniclippt.com/live/v5/474/retro_duck_target_hi.png -O duck_target.png
wget configs-web.agario.miniclippt.com/live/v5/474/retro_bubblesaurus_hi.png -O bubblesaurus.png
wget configs-web.agario.miniclippt.com/live/v5/474/retro_dynamite_guy_hi.png -O dynamite_guy.png
wget configs-web.agario.miniclippt.com/live/v5/474/retro_neon_bug_hi.png -O neon_bug.png
wget configs-web.agario.miniclippt.com/live/v5/474/retro_blue_swirl_hi.png -O blue_swirl.png
wget configs-web.agario.miniclippt.com/live/v5/474/retro_jumper_hi.png -O jumper.png
wget configs-web.agario.miniclippt.com/live/v5/474/chinese_new_year_carp_hi.png -O carp.png
wget configs-web.agario.miniclippt.com/live/v5/474/chinese_new_year_china_dragon_hi.png -O china_dragon.png
wget configs-web.agario.miniclippt.com/live/v5/474/chinese_new_year_dumpling_hi.png -O dumpling.png
wget configs-web.agario.miniclippt.com/live/v5/474/chinese_new_year_chicken_hi.png -O chicken.png
wget configs-web.agario.miniclippt.com/live/v5/474/chinese_new_year_fire_rooster_hi.png -O fire_rooster.png
wget configs-web.agario.miniclippt.com/live/v5/474/rock_stars_heartbreaker_hi.png -O heartbreaker.png
wget configs-web.agario.miniclippt.com/live/v5/474/rock_stars_virtuoso_hi.png -O virtuoso.png
wget configs-web.agario.miniclippt.com/live/v5/474/rock_stars_rocker_hi.png -O rocker.png
wget configs-web.agario.miniclippt.com/live/v5/474/rock_stars_idol_hi.png -O idol.png
wget configs-web.agario.miniclippt.com/live/v5/474/rock_stars_poet_hi.png -O poet.png
wget configs-web.agario.miniclippt.com/live/v5/474/rock_stars_superstar_hi.png -O superstar.png
wget configs-web.agario.miniclippt.com/live/v5/474/rock_stars_bad_boy_hi.png -O bad_boy.png
wget configs-web.agario.miniclippt.com/live/v5/474/master_of_thieves_thief_hi.png -O thief.png
wget configs-web.agario.miniclippt.com/live/v5/474/master_of_thieves_sheriff_hi.png -O sheriff.png
wget configs-web.agario.miniclippt.com/live/v5/474/master_of_thieves_king_hi.png -O king.png
wget configs-web.agario.miniclippt.com/live/v5/474/master_of_thieves_merry_outlaw_hi.png -O merry_outlaw.png
wget configs-web.agario.miniclippt.com/live/v5/474/master_of_thieves_tiny_jack_hi.png -O tiny_jack.png
wget configs-web.agario.miniclippt.com/live/v5/474/master_of_thieves_jade_hi.png -O jade.png
wget configs-web.agario.miniclippt.com/live/v5/474/valentines_day_2017_choco_heart_hi.png -O choco_heart.png
wget configs-web.agario.miniclippt.com/live/v5/474/valentines_day_2017_strawberry_hi.png -O strawberry.png
wget configs-web.agario.miniclippt.com/live/v5/474/valentines_day_2017_love_arrow_hi.png -O love_arrow.png
fdggdf
