wget configs-web.agario.miniclippt.com/live/v9/1037/Banana_hi.png -O banana.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Cookie_hi.png -O cookie.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Jupiter_hi.png -O jupiter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Birdie_hi.png -O birdie.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mercury_hi.png -O mercury.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Apple_hi.png -O apple.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Good_hi.png -O good.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Neptune_hi.png -O neptune.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Blackhole_hi.png -O blackhole.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Uranus_hi.png -O uranus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Starball_hi.png -O starball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Target_hi.png -O target.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Galaxy_hi.png -O galaxy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Venus_hi.png -O venus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Breakfast_hi.png -O breakfast.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Saturn_hi.png -O saturn.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pluto_hi.png -O pluto.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Tiger_Pattern_hi.png -O tigerpattern.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Hot_Dog_hi.png -O hotdog.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Heart_hi.png -O heart.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mouse_hi.png -O mouse.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Wolf_hi.png -O wolf.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Goldfish_hi.png -O goldfish.png
wget configs-web.agario.miniclippt.com/live/v9/1037/pig_hi.png -O pig.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Blueberry_Face_hi.png -O blueberry.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Bomb_hi.png -O bomb.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Bowling_hi.png -O bowling.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Candy_hi.png -O candy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Frog_hi.png -O frog.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Hamburguer_hi.png -O hamburguer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nose_hi.png -O nose.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Seal_hi.png -O seal.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Panda_hi.png -O panda.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pizza_hi.png -O pizza.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Snowman_hi.png -O snowman.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sun_hi.png -O sun.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Baseball_hi.png -O baseball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Basketball_hi.png -O basketball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Bug_hi.png -O bug.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Cloud_hi.png -O cloud.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Muu_hi.png -O muu.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Tomato_Face_hi.png -O tomatoface.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mushroom_hi.png -O mushroom.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Donuts_hi.png -O donuts.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Terrible_hi.png -O terrible.png
wget configs-web.agario.miniclippt.com/live/v9/1037/ghost_hi.png -O ghost.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Apple_Face_hi.png -O appleface.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Turtle_hi.png -O turtle.png
wget configs-web.agario.miniclippt.com/live/v9/1037/BroFist_hi.png -O brofist.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dog_hi.png -O dog.png
wget configs-web.agario.miniclippt.com/live/v9/1037/FootPrint_hi.png -O footprint.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pineapple_Face_hi.png -O pineappleface.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Zebra_Pattern_hi.png -O zebrapattern.png
wget configs-web.agario.miniclippt.com/live/v9/1037/toon_hi.png -O toon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Octopus_hi.png -O octopus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Radar_hi.png -O radar.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Eye_hi.png -O eye.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Owl_hi.png -O owl.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Virus_hi.png -O virus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/smile_hi.png -O smile.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Army_hi.png -O army.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Cat_hi.png -O cat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nuclear_hi.png -O nuclear.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Toxic_hi.png -O toxic.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Doggie_hi.png -O doggie.png
wget configs-web.agario.miniclippt.com/live/v9/1037/face_hi.png -O face.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Willie_hi.png -O willie.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Luchador_hi.png -O luchador.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zombie_hi.png -O zombie.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Bite_hi.png -O bite.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Crazy_hi.png -O crazy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Hockey_hi.png -O hockey.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Jar_Brain_hi.png -O jarbrain.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Evil_hi.png -O evil.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pirate_hi.png -O pirate.png
wget configs-web.agario.miniclippt.com/live/v9/1037/evil_eye_hi.png -O evileye.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Halloween_hi.png -O halloween.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Monster_hi.png -O monster.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Scarecrow_hi.png -O scarecrow.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Spy_hi.png -O spy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/X-mas_hi.png -O santa.png
wget configs-web.agario.miniclippt.com/live/v9/1037/GingerBreadMan_hi.png -O gingerbread.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Grinch_hi.png -O grinch.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Fly_hi.png -O fly.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Spider_hi.png -O spider.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Wasp_hi.png -O wasp.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Lizard_hi.png -O lizard.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Bat_hi.png -O bat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Snake_hi.png -O snake.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Fox_hi.png -O fox.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Coyote_hi.png -O coyote.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Hunter_hi.png -O hunter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sumo_hi.png -O sumo.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Bear_hi.png -O bear.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Cougar_hi.png -O cougar.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Panther_hi.png -O panther.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Lion_hi.png -O lion.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Crocodile_hi.png -O crocodile.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Shark_hi.png -O shark.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mammoth_hi.png -O mammoth.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Raptor_hi.png -O raptor.png
wget configs-web.agario.miniclippt.com/live/v9/1037/T-Rex_hi.png -O t_rex.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Kraken_hi.png -O kraken.png
wget configs-web.agario.miniclippt.com/live/v9/1037/CupCake_hi.png -O cupcake.png
wget configs-web.agario.miniclippt.com/live/v9/1037/KissBoy_hi.png -O kiss_boy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/KissGirl_hi.png -O kiss_girl.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Cupid_hi.png -O cupid.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Shuttle_hi.png -O shuttle.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Astronaut_hi.png -O astronaut.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Laika_hi.png -O space_dog.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Grey_hi.png -O grey.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Comet_hi.png -O meteor.png
wget configs-web.agario.miniclippt.com/live/v9/1037/UFO_hi.png -O ufo.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Rocket_hi.png -O rocket.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Boot_hi.png -O boot.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Gold_Pot_hi.png -O gold_pot.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Hat_hi.png -O hat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Horse_Shoe_hi.png -O horse_shoe.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Leaf_Clover_hi.png -O leaf_clover.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Leprechaun_hi.png -O leprechaun.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Rainbow_hi.png -O rainbow.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Choco_Egg_hi.png -O choco_egg.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Carrot_hi.png -O carrot.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Easter_Island_hi.png -O easter_island.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Rooster_hi.png -O rooster.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Rabbit_hi.png -O rabbit.png
wget configs-web.agario.miniclippt.com/live/v9/1037/AprilFool_hi.png -O april_fool.png
wget configs-web.agario.miniclippt.com/live/v9/1037/EarthDay_hi.png -O earth_day.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Chihuahua_hi.png -O chihuahua.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Cactus_hi.png -O cactus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sombrero_hi.png -O sombrero.png
wget configs-web.agario.miniclippt.com/live/v9/1037/ChilliPepper_hi.png -O hot_pepper.png
wget configs-web.agario.miniclippt.com/live/v9/1037/ChupaCabra_hi.png -O chupacabra.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Tortilha_hi.png -O taco.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pinhata_hi.png -O pinata.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dragon_hi.png -O dragon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Gargoyle_hi.png -O gargoyle.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Gopher_hi.png -O gopher.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sheep_hi.png -O sheep.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Thirteen_hi.png -O thirteen.png
wget configs-web.agario.miniclippt.com/live/v9/1037/BlackCat_hi.png -O black_cat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Crow_hi.png -O crow.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mask_hi.png -O mask.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Witch_hi.png -O goblin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/GreenMan_hi.png -O greenman.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SlimeFace_hi.png -O slimeface.png
wget configs-web.agario.miniclippt.com/live/v9/1037/JellyBlob_hi.png -O jellyblob.png
wget configs-web.agario.miniclippt.com/live/v9/1037/AlienX_hi.png -O invader.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SpaceHunter_hi.png -O spacehunter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Soccer_Ball_hi.png -O soccerball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Glub_hi.png -O glub.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Soccer_Shoe_hi.png -O soccer_shoe.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Player_2_hi.png -O striker.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Player_1_hi.png -O starplayer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/TenderHeart_Bear_hi.png -O tender_heart_bear.png
wget configs-web.agario.miniclippt.com/live/v9/1037/FunShine_Bear_hi.png -O funshine_bear.png
wget configs-web.agario.miniclippt.com/live/v9/1037/BrightHeart_Racoon_hi.png -O bright_heart_raccoon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/CozyHeart_Penguin_hi.png -O cozy_heart_penguin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/LotsaHeart_Elephant_hi.png -O lotsa_heart_elephant.png
wget configs-web.agario.miniclippt.com/live/v9/1037/BraveHeart_Lion_hi.png -O brave_heart_lion.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Crazy_Ball_hi.png -O crazy_ball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sky_Rocket_hi.png -O skyrocket.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Stars_and_Stripes_hi.png -O stars_stripes.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mighty_hi.png -O mighty.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Uncle_Sam_hi.png -O uncle_sam.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Eagle_hi.png -O eagle.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Liberty_hi.png -O liberty.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mummy_Ball_hi.png -O dust_brain.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Eye_Ball_hi.png -O oculus_orbus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/BaseballSmile_Ball_hi.png -O screamin_meamie.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Cyclop_Ball_hi.png -O hornhead.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SkullBrain_Ball_hi.png -O skull_face.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sunbath_hi.png -O sunbath.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Watermelon_hi.png -O watermelon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/StarFish_hi.png -O starfish.png
wget configs-web.agario.miniclippt.com/live/v9/1037/IcecreamFace_hi.png -O icecream.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Surfer_hi.png -O surfer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Diver_hi.png -O diver.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_sanik_hi.png -O birthday_sanik.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_wojak_hi.png -O birthday_wojak.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_cia_hi.png -O birthday_cia.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_sir_hi.png -O birthday_sir.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_doge_hi.png -O birthday_doge.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_lol_hi.png -O birthday_lol.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_troll_hi.png -O birthday_troll.png
wget configs-web.agario.miniclippt.com/live/v9/1037/food_Cofee_hi.png -O hot_coffee.png
wget configs-web.agario.miniclippt.com/live/v9/1037/food_Juice_Can_hi.png -O soda_can.png
wget configs-web.agario.miniclippt.com/live/v9/1037/food_Jelly_Face_hi.png -O jelly.png
wget configs-web.agario.miniclippt.com/live/v9/1037/food_French_Fries_hi.png -O fries.png
wget configs-web.agario.miniclippt.com/live/v9/1037/food_Hamburguer_hi.png -O burger_face.png
wget configs-web.agario.miniclippt.com/live/v9/1037/food_Terminita_hi.png -O hard_shroom.png
wget configs-web.agario.miniclippt.com/live/v9/1037/food_Chicken_Leg_hi.png -O drumstick.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rio_tennis_hi.png -O tennist.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rio_gymnastic_hi.png -O gymnast.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rio_judo_hi.png -O judo_fighter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rio_swimmer_hi.png -O swimmer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rio_athletic_hi.png -O sprinter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rio_mico_hi.png -O mico.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rio_toco_hi.png -O toco.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pirates_Parrot_hi.png -O parrot.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pirates_Rascal_hi.png -O rascal.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pirates_PirateGirl_hi.png -O pirate_maiden.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pirates_SkullPirate_hi.png -O captain_skull.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pirates_Captain_hi.png -O black_beard.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pirates_CannonBall_hi.png -O cannonball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pirates_Monkey_hi.png -O mad_monkey.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sports_Target_hi.png -O bullseye.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sports_Fencing_hi.png -O touche.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sports_BoxingGlub_hi.png -O jab.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sports_Golf_hi.png -O backswing.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sports_Volleyball_hi.png -O spike.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sports_PingPong_hi.png -O smash.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Sports_Basketball_hi.png -O dunk.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Alien2_Gamma_hi.png -O gamma.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Alien2_Neila_hi.png -O neila.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Alien2_Omicron_hi.png -O omicron.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Alien2_Vega_hi.png -O vega.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Alien2_Smyg_hi.png -O smyg.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Journey_WhiteHorse_hi.png -O white_horse.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Journey_Monk_hi.png -O monk.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Journey_WaterSpirit_hi.png -O water_spirit.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Journey_Boar_hi.png -O boar.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Journey_Kong_hi.png -O kong.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Journey_BullKing_hi.png -O bull_king.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Journey_JadeDragon_hi.png -O jade_dragon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Treasure_Squiggly_hi.png -O treasure_squiggly.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Treasure_SeaExplorer_hi.png -O treasure_explorer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Autumn_Squirrel_hi.png -O squirrel.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Autumn_Acorn_hi.png -O acorn.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Autumn_Maple_hi.png -O maple.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Autumn_Badger_hi.png -O badger.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Autumn_Prey_hi.png -O prey.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Autumn_Sly_hi.png -O sly.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Autumn_Faun_hi.png -O faun.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Island_Pinehead_hi.png -O pinehead.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Island_Sea_Turtle_hi.png -O sea_turtle.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Island_Volcano_hi.png -O volcano.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Island_Coconuts_hi.png -O coconuts.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Island_Warrior_hi.png -O warrior.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Island_Seer_hi.png -O seer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Island_Scar_hi.png -O scar.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dead_Viper_hi.png -O viper.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dead_Biker_hi.png -O biker.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dead_DesertFox_hi.png -O desert_fox.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dead_Ranger_hi.png -O ranger.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dead_Devourer_hi.png -O devourer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dead_Raider_hi.png -O raider.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dead_Nuke_hi.png -O nuke.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nuclear_ToxicEater_hi.png -O toxic_eater.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nuclear_Ogre_hi.png -O ogre.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nuclear_Scavenger_hi.png -O scavenger.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nuclear_Marauder_hi.png -O marauder.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nuclear_Mutant_hi.png -O mutant.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nuclear_Ooze_hi.png -O ooze.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Nuclear_Hazmat_hi.png -O hazmat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/HappyWeekend_Croc_hi.png -O happy_croc.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Undead_hi.png -O undead.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Phantom_hi.png -O phantom.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Werewolf_hi.png -O werewolf.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mummy_hi.png -O mummy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Vampire_hi.png -O vampire.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Frankenstein_hi.png -O frankenstein.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pumpkin_hi.png -O pumpkin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Masked_hi.png -O masked.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Skull_Cactus_hi.png -O skull_cactus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Skeleton_hi.png -O skeleton.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Infernando_hi.png -O infernando.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Calavera_hi.png -O calavera.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Poison_Rose_hi.png -O poison_rose.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Calaca_hi.png -O calaca.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SH_MajorEagle_hi.png -O major_eagle.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SH_X_Ray_hi.png -O xray.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SH_TigerMan_hi.png -O the_tiger.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SH_StarGirl_hi.png -O star_sentinel.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SH_IronKnight_hi.png -O iron_titan.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SH_ArachnoKid_hi.png -O cyber_kid.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SH_OmegaBlast_hi.png -O omega_blast.png
wget configs-web.agario.miniclippt.com/live/v9/1037/SH_DrCosmos_hi.png -O dr_cosmos.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Terra_hi.png -O terra.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Aqua_hi.png -O aqua.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Aer_hi.png -O aer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Ignis_hi.png -O ignis.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Colossus_hi.png -O colossus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Dark_Matter_hi.png -O dark_matter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pie_Slice_hi.png -O pie_slice.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pilgrim_hi.png -O pilgrim.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Virginia_hi.png -O virginia.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Thanksgiving_Turkey_hi.png -O turkey.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Mr_Pumpkin_hi.png -O mr_pumpkin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Happy_hi.png -O happy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Bread_hi.png -O bread.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Pug_hi.png -O pug.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Winter_Wolf_hi.png -O winter_wolf.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Viking_hi.png -O viking.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Icy_Braid_hi.png -O icy_braid.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Berserker_hi.png -O berserker.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Champion_hi.png -O champion.png
wget configs-web.agario.miniclippt.com/live/v9/1037/Jotun_hi.png -O jotun.png
wget configs-web.agario.miniclippt.com/live/v9/1037/ArcheryKing_Skin_hi.png -O archery_king.png
wget configs-web.agario.miniclippt.com/live/v9/1037/creatures_root_gnome_hi.png -O root_gnome.png
wget configs-web.agario.miniclippt.com/live/v9/1037/creatures_hobgoblin_hi.png -O hobgoblin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/creatures_pixie_hi.png -O pixie.png
wget configs-web.agario.miniclippt.com/live/v9/1037/creatures_basilisk_hi.png -O basilisk.png
wget configs-web.agario.miniclippt.com/live/v9/1037/creatures_firebird_hi.png -O firebird.png
wget configs-web.agario.miniclippt.com/live/v9/1037/creatures_magic_gerbil_hi.png -O magic_gerbil.png
wget configs-web.agario.miniclippt.com/live/v9/1037/creatures_gryphon_hi.png -O gryphon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/creatures_dark_wings_hi.png -O dark_wings.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dawn_cyber_guard_hi.png -O cyber_guard.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dawn_star_pilot_hi.png -O star_pilot.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dawn_cosmo_pirate_hi.png -O cosmo_pirate.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dawn_moon_ship_hi.png -O moon_ship.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dawn_space_warden_hi.png -O space_warden.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dawn_evil_master_hi.png -O evil_master.png
wget configs-web.agario.miniclippt.com/live/v9/1037/xmas_2016_reindeer_hi.png -O reindeer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/xmas_2016_elf_helper_hi.png -O elf_helper.png
wget configs-web.agario.miniclippt.com/live/v9/1037/xmas_2016_santa_claus_hi.png -O santa_claus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/xmas_2016_polar_bear_hi.png -O polar_bear.png
wget configs-web.agario.miniclippt.com/live/v9/1037/xmas_2016_penguin_hi.png -O penguin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/new_year_2016_flying_cork_hi.png -O flying_cork.png
wget configs-web.agario.miniclippt.com/live/v9/1037/new_year_2016_happy_soda_hi.png -O happy_soda.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_goat_hi.png -O bruiser_goat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_bunny_hi.png -O rogue_bunny.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_rhino_hi.png -O rhino_boxer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_bull_hi.png -O street_bull.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_husky_hi.png -O husky_brawl.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_tiger_hi.png -O kempo_tiger.png
wget configs-web.agario.miniclippt.com/live/v9/1037/time_travel_best_friends_hi.png -O best_friends.png
wget configs-web.agario.miniclippt.com/live/v9/1037/time_travel_chrono_ranger_hi.png -O chrono_ranger.png
wget configs-web.agario.miniclippt.com/live/v9/1037/time_travel_cool_agent_hi.png -O cool_agent.png
wget configs-web.agario.miniclippt.com/live/v9/1037/time_travel_time_dude_hi.png -O time_dude.png
wget configs-web.agario.miniclippt.com/live/v9/1037/time_travel_time_doctor_hi.png -O time_doctor.png
wget configs-web.agario.miniclippt.com/live/v9/1037/friday_the_13th_2017_wicked_cat_hi.png -O wicked_cat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/retro_duck_target_hi.png -O duck_target.png
wget configs-web.agario.miniclippt.com/live/v9/1037/retro_bubblesaurus_hi.png -O bubblesaurus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/retro_dynamite_guy_hi.png -O dynamite_guy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/retro_neon_bug_hi.png -O neon_bug.png
wget configs-web.agario.miniclippt.com/live/v9/1037/retro_blue_swirl_hi.png -O blue_swirl.png
wget configs-web.agario.miniclippt.com/live/v9/1037/retro_jumper_hi.png -O jumper.png
wget configs-web.agario.miniclippt.com/live/v9/1037/chinese_new_year_carp_hi.png -O carp.png
wget configs-web.agario.miniclippt.com/live/v9/1037/chinese_new_year_china_dragon_hi.png -O china_dragon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/chinese_new_year_dumpling_hi.png -O dumpling.png
wget configs-web.agario.miniclippt.com/live/v9/1037/chinese_new_year_chicken_hi.png -O chicken.png
wget configs-web.agario.miniclippt.com/live/v9/1037/chinese_new_year_fire_rooster_hi.png -O fire_rooster.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_stars_heartbreaker_hi.png -O heartbreaker.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_stars_virtuoso_hi.png -O virtuoso.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_stars_rocker_hi.png -O rocker.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_stars_idol_hi.png -O idol.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_stars_poet_hi.png -O poet.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_stars_superstar_hi.png -O superstar.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_stars_bad_boy_hi.png -O bad_boy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/master_of_thieves_thief_hi.png -O thief.png
wget configs-web.agario.miniclippt.com/live/v9/1037/master_of_thieves_sheriff_hi.png -O sheriff.png
wget configs-web.agario.miniclippt.com/live/v9/1037/master_of_thieves_king_hi.png -O king.png
wget configs-web.agario.miniclippt.com/live/v9/1037/master_of_thieves_merry_outlaw_hi.png -O merry_outlaw.png
wget configs-web.agario.miniclippt.com/live/v9/1037/master_of_thieves_tiny_jack_hi.png -O tiny_jack.png
wget configs-web.agario.miniclippt.com/live/v9/1037/master_of_thieves_jade_hi.png -O jade.png
wget configs-web.agario.miniclippt.com/live/v9/1037/valentines_day_2017_choco_heart_hi.png -O choco_heart.png
wget configs-web.agario.miniclippt.com/live/v9/1037/valentines_day_2017_strawberry_hi.png -O strawberry.png
wget configs-web.agario.miniclippt.com/live/v9/1037/valentines_day_2017_love_arrow_hi.png -O love_arrow.png
wget configs-web.agario.miniclippt.com/live/v9/1037/monthly_web_bunny_hi.png -O bunny.png
wget configs-web.agario.miniclippt.com/live/v9/1037/carnival_2017_palm_tree_hi.png -O palm_tree.png
wget configs-web.agario.miniclippt.com/live/v9/1037/carnival_2017_samba_hi.png -O samba.png
wget configs-web.agario.miniclippt.com/live/v9/1037/carnival_2017_mountain_hi.png -O mountain.png
wget configs-web.agario.miniclippt.com/live/v9/1037/carnival_2017_bird_mask_hi.png -O bird_mask.png
wget configs-web.agario.miniclippt.com/live/v9/1037/carnival_2017_trickster_hi.png -O trickster.png
wget configs-web.agario.miniclippt.com/live/v9/1037/carnival_2017_golden_mask_hi.png -O golden_mask.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_legends_2_performer_hi.png -O performer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_legends_2_diva_hi.png -O diva.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_legends_2_songsmith_hi.png -O songsmith.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_legends_2_icon_hi.png -O icon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_legends_2_metal_face_hi.png -O metal_face.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rock_legends_2_soloist_hi.png -O soloist.png
wget configs-web.agario.miniclippt.com/live/v9/1037/jungle_quest_huntsman_hi.png -O huntsman.png
wget configs-web.agario.miniclippt.com/live/v9/1037/jungle_quest_war_paint_hi.png -O war_paint.png
wget configs-web.agario.miniclippt.com/live/v9/1037/jungle_quest_behemoth_hi.png -O behemoth.png
wget configs-web.agario.miniclippt.com/live/v9/1037/jungle_quest_general_hi.png -O general.png
wget configs-web.agario.miniclippt.com/live/v9/1037/jungle_quest_giant_skull_hi.png -O giant_skull.png
wget configs-web.agario.miniclippt.com/live/v9/1037/jungle_quest_great_zilla_hi.png -O great_zilla.png
wget configs-web.agario.miniclippt.com/live/v9/1037/st_patricks_2017_horse_boot_hi.png -O horse_boot.png
wget configs-web.agario.miniclippt.com/live/v9/1037/st_patricks_2017_happy_hat_hi.png -O happy_hat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/st_patricks_2017_bad_clover_hi.png -O bad_clover.png
wget configs-web.agario.miniclippt.com/live/v9/1037/st_patricks_2017_gold_rush_hi.png -O gold_rush.png
wget configs-web.agario.miniclippt.com/live/v9/1037/st_patricks_2017_red_beard_hi.png -O red_beard.png
wget configs-web.agario.miniclippt.com/live/v9/1037/st_patricks_2017_cloud_prism_hi.png -O cloud_prism.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_aries_hi.png -O aries.png
wget configs-web.agario.miniclippt.com/live/v9/1037/monthly_web_coil_hi.png -O coil.png
wget configs-web.agario.miniclippt.com/live/v9/1037/excalibur_2017_cat_cauldron_hi.png -O cat_cauldron.png
wget configs-web.agario.miniclippt.com/live/v9/1037/excalibur_2017_seal_knight_hi.png -O seal_knight.png
wget configs-web.agario.miniclippt.com/live/v9/1037/excalibur_2017_mystic_bird_hi.png -O mystic_bird.png
wget configs-web.agario.miniclippt.com/live/v9/1037/excalibur_2017_king_lion_hi.png -O king_lion.png
wget configs-web.agario.miniclippt.com/live/v9/1037/excalibur_2017_excalibur_hi.png -O excalibur.png
wget configs-web.agario.miniclippt.com/live/v9/1037/excalibur_2017_magic_hat_hi.png -O magic_hat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/april_fools_2017_funny_face_hi.png -O funny_face.png
wget configs-web.agario.miniclippt.com/live/v9/1037/april_fools_2017_air_bag_hi.png -O air_bag.png
wget configs-web.agario.miniclippt.com/live/v9/1037/april_fools_2017_smelly_hi.png -O smelly.png
wget configs-web.agario.miniclippt.com/live/v9/1037/ghost_machine_cyber_agent_hi.png -O cyber_agent.png
wget configs-web.agario.miniclippt.com/live/v9/1037/ghost_machine_droid_hi.png -O droid.png
wget configs-web.agario.miniclippt.com/live/v9/1037/ghost_machine_detective_hi.png -O detective.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_ii_skin_karate_parrot_hi.png -O karate_parrot.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_ii_skin_raccoon_jutsu_hi.png -O raccoon_jutsu.png
wget configs-web.agario.miniclippt.com/live/v9/1037/beast_fighters_ii_skin_frog_thai_hi.png -O frog_thai.png
wget configs-web.agario.miniclippt.com/live/v9/1037/easter_2017_easter_chick_hi.png -O easter_chick.png
wget configs-web.agario.miniclippt.com/live/v9/1037/easter_2017_wacky_egg_hi.png -O wacky_egg.png
wget configs-web.agario.miniclippt.com/live/v9/1037/easter_2017_cool_bunny_hi.png -O cool_bunny.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_skin_taurus_hi.png -O taurus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v1_skin_destroyer_hi.png -O destroyer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v1_skin_storm_fist_hi.png -O storm_fist.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v1_skin_war_hero_hi.png -O war_hero.png
wget configs-web.agario.miniclippt.com/live/v9/1037/monthly_web_eyeball_hi.png -O eyeball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/space_pirates_starfighter_hi.png -O starfighter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/space_pirates_power_badger_hi.png -O power_badger.png
wget configs-web.agario.miniclippt.com/live/v9/1037/space_pirates_alien_tree_hi.png -O alien_tree.png
wget configs-web.agario.miniclippt.com/live/v9/1037/cinco_mayo_2017_crazy_sombrero_hi.png -O crazy_sombrero.png
wget configs-web.agario.miniclippt.com/live/v9/1037/cinco_mayo_2017_maracas_hi.png -O maracas.png
wget configs-web.agario.miniclippt.com/live/v9/1037/cinco_mayo_2017_hot_taco_hi.png -O hot_taco.png
wget configs-web.agario.miniclippt.com/live/v9/1037/stone_age_sabertooth_hi.png -O sabertooth.png
wget configs-web.agario.miniclippt.com/live/v9/1037/stone_age_silver_tusk_hi.png -O silver_tusk.png
wget configs-web.agario.miniclippt.com/live/v9/1037/stone_age_primal_hi.png -O primal.png
wget configs-web.agario.miniclippt.com/live/v9/1037/stone_age_amber_hi.png -O amber.png
wget configs-web.agario.miniclippt.com/live/v9/1037/stone_age_stone_tool_hi.png -O stone_tool.png
wget configs-web.agario.miniclippt.com/live/v9/1037/stone_age_fire_face_hi.png -O fire_face.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_skin_gemini_hi.png -O gemini.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_wacky_hero_hi.png -O wacky_hero.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_fallen_hi.png -O fallen.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_power_girl_hi.png -O power_girl.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_skull_ribbon_hi.png -O skull_ribbon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_eyepatch_hi.png -O eyepatch.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_mega_power_hi.png -O mega_power.png
wget configs-web.agario.miniclippt.com/live/v9/1037/pet_balls_jellyfish_hi.png -O jellyfish_ball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/pet_balls_walrus_hi.png -O walrus_ball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/pet_balls_bat_hi.png -O bat_ball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/pet_balls_elephant_hi.png -O elephant_ball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/pet_balls_sheep_hi.png -O sheep_ball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/pet_balls_pig_hi.png -O pig_ball.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v2_apocalypse_rider_hi.png -O apocalypse_rider.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v2_eclipse_hunter_hi.png -O eclipse_hunter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v2_universal_ranger_hi.png -O universal_ranger.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v2_slaughter_hi.png -O slaughter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v2_slingblade_hi.png -O slingblade.png
wget configs-web.agario.miniclippt.com/live/v9/1037/action_heroes_v2_the_professional_hi.png -O the_professional.png
wget configs-web.agario.miniclippt.com/live/v9/1037/mechanos_sonic_boom_hi.png -O sonic_boom.png
wget configs-web.agario.miniclippt.com/live/v9/1037/mechanos_cyber_scarab_hi.png -O cyber_scarab.png
wget configs-web.agario.miniclippt.com/live/v9/1037/mechanos_haste_hi.png -O haste.png
wget configs-web.agario.miniclippt.com/live/v9/1037/mechanos_psycho_driller_hi.png -O psycho_driller.png
wget configs-web.agario.miniclippt.com/live/v9/1037/mechanos_supremus_hi.png -O supremus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/mechanos_yellow_streak_hi.png -O yellow_streak.png
wget configs-web.agario.miniclippt.com/live/v9/1037/mechanos_mechatron_hi.png -O mechatron.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_cancer_hi.png -O cancer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/independence_day_2017_star_eagle_hi.png -O star_eagle.png
wget configs-web.agario.miniclippt.com/live/v9/1037/independence_day_2017_celebration_hat_hi.png -O celebration_hat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/independence_day_2017_mr_boss_hi.png -O mr_boss.png
wget configs-web.agario.miniclippt.com/live/v9/1037/monthly_web_fury_cat_hi.png -O fury_cat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/gladiators_helm_hi.png -O helm.png
wget configs-web.agario.miniclippt.com/live/v9/1037/gladiators_gladiatrix_hi.png -O gladiatrix.png
wget configs-web.agario.miniclippt.com/live/v9/1037/gladiators_reptilian_hi.png -O reptilian.png
wget configs-web.agario.miniclippt.com/live/v9/1037/gladiators_orc_grunt_hi.png -O orc_grunt.png
wget configs-web.agario.miniclippt.com/live/v9/1037/gladiators_cursed_blade_hi.png -O cursed_blade.png
wget configs-web.agario.miniclippt.com/live/v9/1037/gladiators_orc_warrior_hi.png -O orc_warrior.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_hungry_hi.png -O hungry.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_queasy_hi.png -O queasy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_lovesick_hi.png -O lovesick.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_sad_hi.png -O sad.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_bitter_hi.png -O bitter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_amazed_hi.png -O amazed.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_odd_hi.png -O odd.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_funky_hi.png -O funky.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_angry_hi.png -O angry.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_1_vicious_hi.png -O vicious.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_skin_leo_hi.png -O leo.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_sweaty_hi.png -O sweaty.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_wicked_hi.png -O wicked.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_full_hi.png -O full.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_tough_hi.png -O tough.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_mischievous_hi.png -O mischievous.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_dazzled_hi.png -O dazzled.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_nerdy_hi.png -O nerdy.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_rabid_hi.png -O rabid.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_delighted_hi.png -O delighted.png
wget configs-web.agario.miniclippt.com/live/v9/1037/birthday_2017_2_cool_hi.png -O cool.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zombie_party_dry_face_hi.png -O dry_face.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zombie_party_crazy_brain_hi.png -O crazy_brain.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zombie_party_zombie_dog_hi.png -O zombie_dog.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zombie_party_zombie_party_hi.png -O zombie_party.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zombie_party_walking_hand_hi.png -O walking_hand.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zombie_party_the_maw_hi.png -O the_maw.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rpg_games_rogue_hi.png -O rogue.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rpg_games_archer_hi.png -O archer.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rpg_games_paladin_hi.png -O paladin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rpg_games_mage_hi.png -O mage.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rpg_games_scroll_hi.png -O scroll.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rpg_games_raid_boss_hi.png -O raid_boss.png
wget configs-web.agario.miniclippt.com/live/v9/1037/rpg_games_healing_potion_hi.png -O healing_potion.png
wget configs-web.agario.miniclippt.com/live/v9/1037/arcade_games_gold_coin_hi.png -O gold_coin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/arcade_games_super_car_hi.png -O super_car.png
wget configs-web.agario.miniclippt.com/live/v9/1037/arcade_games_war_tank_hi.png -O war_tank.png
wget configs-web.agario.miniclippt.com/live/v9/1037/arcade_games_pixel_kong_hi.png -O pixel_kong.png
wget configs-web.agario.miniclippt.com/live/v9/1037/arcade_games_power_fighter_hi.png -O power_fighter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/arcade_games_techno_kid_hi.png -O techno_kid.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_virgo_hi.png -O virgo.png
wget configs-web.agario.miniclippt.com/live/v9/1037/war_wings_hi.png -O war_wings.png
wget configs-web.agario.miniclippt.com/live/v9/1037/olympus_hercules_hi.png -O olympus_hercules.png
wget configs-web.agario.miniclippt.com/live/v9/1037/olympus_poseidon_hi.png -O olympus_poseidon.png
wget configs-web.agario.miniclippt.com/live/v9/1037/olympus_medusa_hi.png -O olympus_medusa.png
wget configs-web.agario.miniclippt.com/live/v9/1037/olympus_hades_hi.png -O olympus_hades.png
wget configs-web.agario.miniclippt.com/live/v9/1037/olympus_ares_hi.png -O olympus_ares.png
wget configs-web.agario.miniclippt.com/live/v9/1037/olympus_zeus_hi.png -O olympus_zeus.png
wget configs-web.agario.miniclippt.com/live/v9/1037/nvr_zap_hi.png -O nvr_zap.png
wget configs-web.agario.miniclippt.com/live/v9/1037/nvr_silent_fox_hi.png -O nvr_silent_fox.png
wget configs-web.agario.miniclippt.com/live/v9/1037/nvr_insectoid_hi.png -O nvr_insectoid.png
wget configs-web.agario.miniclippt.com/live/v9/1037/nvr_shuriken_hi.png -O nvr_shuriken.png
wget configs-web.agario.miniclippt.com/live/v9/1037/nvr_steel_ram_hi.png -O nvr_steel_ram.png
wget configs-web.agario.miniclippt.com/live/v9/1037/nvr_shadow_hi.png -O nvr_shadow.png
wget configs-web.agario.miniclippt.com/live/v9/1037/football_strike_hi.png -O football_strike.png
wget configs-web.agario.miniclippt.com/live/v9/1037/steamworld_cogs_hi.png -O steamworld_cogs.png
wget configs-web.agario.miniclippt.com/live/v9/1037/steamworld_dr_static_hi.png -O steamworld_dr_static.png
wget configs-web.agario.miniclippt.com/live/v9/1037/steamworld_steam_freak_hi.png -O steamworld_steam_freak.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dragon_griffin_hi.png -O dragon_griffin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dragon_twin_hi.png -O dragon_twin.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dragon_hydra_hi.png -O dragon_hydra.png
wget configs-web.agario.miniclippt.com/live/v9/1037/steamworld_think_tank_hi.png -O steamworld_think_tank.png
wget configs-web.agario.miniclippt.com/live/v9/1037/steamworld_can_man_hi.png -O steamworld_can_man.png
wget configs-web.agario.miniclippt.com/live/v9/1037/steamworld_the_tinker_hi.png -O steamworld_the_tinker.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dragon_razor_hi.png -O dragon_razor.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dragon_haze_hi.png -O dragon_haze.png
wget configs-web.agario.miniclippt.com/live/v9/1037/dragon_viper_hi.png -O dragon_viper.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_libra_hi.png -O zodiac_2017_libra.png
wget configs-web.agario.miniclippt.com/live/v9/1037/egypt_ankh_hi.png -O egypt_ankh.png
wget configs-web.agario.miniclippt.com/live/v9/1037/egypt_cleopatra_hi.png -O egypt_cleopatra.png
wget configs-web.agario.miniclippt.com/live/v9/1037/egypt_pharaoh_hi.png -O egypt_pharaoh.png
wget configs-web.agario.miniclippt.com/live/v9/1037/egypt_egyptian_cat_hi.png -O egypt_egyptian_cat.png
wget configs-web.agario.miniclippt.com/live/v9/1037/egypt_scarab_hi.png -O egypt_scarab.png
wget configs-web.agario.miniclippt.com/live/v9/1037/egypt_mummy_king_hi.png -O egypt_mummy_king.png
wget configs-web.agario.miniclippt.com/live/v9/1037/egypt_anubis_hi.png -O egypt_anubis.png
wget configs-web.agario.miniclippt.com/live/v9/1037/samurai_shogun_hi.png -O shogun.png
wget configs-web.agario.miniclippt.com/live/v9/1037/samurai_elder_master_hi.png -O elder_master.png
wget configs-web.agario.miniclippt.com/live/v9/1037/samurai_geisha_hi.png -O geisha.png
wget configs-web.agario.miniclippt.com/live/v9/1037/samurai_war_mask_hi.png -O war_mask.png
wget configs-web.agario.miniclippt.com/live/v9/1037/samurai_rogue_samurai_hi.png -O rogue_samurai.png
wget configs-web.agario.miniclippt.com/live/v9/1037/samurai_skull_samurai_hi.png -O skull_samurai.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_skin_scorpio_hi.png -O zodiac_2017_scorpio.png
wget configs-web.agario.miniclippt.com/live/v9/1037/moonlight_metal_ghoul_hi.png -O moonlight_metal_ghoul.png
wget configs-web.agario.miniclippt.com/live/v9/1037/moonlight_psycho_hi.png -O moonlight_psycho.png
wget configs-web.agario.miniclippt.com/live/v9/1037/moonlight_banshee_hi.png -O moonlight_banshee.png
wget configs-web.agario.miniclippt.com/live/v9/1037/moonlight_wendigo_hi.png -O moonlight_wendigo.png
wget configs-web.agario.miniclippt.com/live/v9/1037/moonlight_red_fiend_hi.png -O moonlight_red_fiend.png
wget configs-web.agario.miniclippt.com/live/v9/1037/moonlight_night_hunter_hi.png -O moonlight_night_hunter.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_mega_mecha_hi.png -O mega_mecha.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_spinner_kid_hi.png -O spinner_kid.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_bolt_samurai_hi.png -O bolt_samurai.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_skull_bow_hi.png -O skull_bow.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_power_ninja_hi.png -O power_ninja.png
wget configs-web.agario.miniclippt.com/live/v9/1037/anime_giant_human_hi.png -O giant_human.png
wget configs-web.agario.miniclippt.com/live/v9/1037/monthly_web_husky_hi.png -O husky.png
wget configs-web.agario.miniclippt.com/live/v9/1037/winter_snowboarder_hi.png -O winter_snowboarder.png
wget configs-web.agario.miniclippt.com/live/v9/1037/winter_white_owl_hi.png -O winter_white_owl.png
wget configs-web.agario.miniclippt.com/live/v9/1037/winter_goofy_yeti_hi.png -O winter_goofy_yeti.png
wget configs-web.agario.miniclippt.com/live/v9/1037/winter_ice_crystal_hi.png -O winter_ice_crystal.png
wget configs-web.agario.miniclippt.com/live/v9/1037/winter_dire_wolf_hi.png -O winter_dire_wolf.png
wget configs-web.agario.miniclippt.com/live/v9/1037/winter_ice_lord_hi.png -O winter_ice_lord.png
wget configs-web.agario.miniclippt.com/live/v9/1037/zodiac_2017_sagittarius_hi.png -O zodiac_2017_sagittarius.png
